# Ronaldo Analysis

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r'E:\Data Analyst Roadmap\Google Data Analytics Certificate Course\Different Analysis\Ronaldo Goals Analysis\Data Cleaning In Python\Ronaldo_Analysis.csv')

In [3]:
df

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
0,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,34,2:00,Solo run,NaN
1,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,90+5,3:00,Header,Rui Jorge
2,02/03,Liga Portugal,8,10/26/02,A,Sporting CP,Boavista FC,1:02,NaN,88,1:02,Right-footed shot,Carlos Martins
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,H,Sporting CP,CD Estarreja,4:01,NaN,67,3:00,Left-footed shot,Cesar Prates
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,H,Sporting CP,FC Oliveira do Hospital,8:01,NaN,13,3:00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,22/23,Saudi Pro League,16,2/9/23,A,Al-Nassr FC,Al-Wehda FC,0:4,CF,61,0:4,Right-footed shot,NaN
706,22/23,Saudi Pro League,18,2/25/23,A,Al-Nassr FC,Damac FC,0:3,CF,18,0:1,Penalty,\t
707,22/23,Saudi Pro League,18,2/25/23,A,Al-Nassr FC,Damac FC,0:3,CF,23,0:2,Left-footed shot,Sultan Al-Ghannam
708,22/23,Saudi Pro League,18,2/25/23,A,Al-Nassr FC,Damac FC,0:3,CF,44,0:3,Counter attack goal,Ayman Yahya
709,22/23,Saudi Pro League,21,3/18/23,H,Al-Nassr FC,Abha Club,2:1,CF,78,1:1,Direct free kick,NaN

In [4]:
df.head(10)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
0,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,34,2:00,Solo run,NaN
1,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,90+5,3:00,Header,Rui Jorge
2,02/03,Liga Portugal,8,10/26/02,A,Sporting CP,Boavista FC,1:02,NaN,88,1:02,Right-footed shot,Carlos Martins
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,H,Sporting CP,CD Estarreja,4:01,NaN,67,3:00,Left-footed shot,Cesar Prates
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,H,Sporting CP,FC Oliveira do Hospital,8:01,NaN,13,3:00,NaN,NaN
5,03/04,Premier League,11,11-01-03,H,Manchester United,Portsmouth FC,3:00,RW,80,2:00,Direct free kick,NaN
6,03/04,FA Cup,Fifth Round,2/14/04,H,Manchester United,Manchester City,4:02,RW,74,3:00,Right-footed shot,NaN
7,03/04,Premier League,29,3/20/04,H,Manchester United,Tottenham Hotspur,3:00,NaN,89,2:00,Right-footed shot,NaN
8,03/04,Premier League,32,04-10-04,A,Manchester United,Birmingham City,1:02,NaN,60,1:01,Header,Ryan Giggs
9,03/04,Premier League,38,5/15/04,A,Manchester United,Aston Villa,0:02,NaN,4,0:01,Right-footed shot,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Season            710 non-null    object
 1   Competition       710 non-null    object
 2   Matchday          710 non-null    object
 3   Date              710 non-null    object
 4   Venue             710 non-null    object
 5   Club              710 non-null    object
 6   Opponent          710 non-null    object
 7   Result            710 non-null    object
 8   Playing_Position  652 non-null    object
 9   Minute            710 non-null    object
 10  At_score          710 non-null    object
 11  Type              695 non-null    object
 12  Goal_assist       464 non-null    object
dtypes: object(13)
memory usage: 72.2+ KB

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Season            710 non-null    object
 1   Competition       710 non-null    object
 2   Matchday          710 non-null    object
 3   Date              710 non-null    object
 4   Venue             710 non-null    object
 5   Club              710 non-null    object
 6   Opponent          710 non-null    object
 7   Result            710 non-null    object
 8   Playing_Position  652 non-null    object
 9   Minute            710 non-null    object
 10  At_score          710 non-null    object
 11  Type              695 non-null    object
 12  Goal_assist       464 non-null    object
dtypes: object(13)
memory usage: 72.2+ KB

In [7]:
df.head(10)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
0,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,34,2:00,Solo run,NaN
1,02/03,Liga Portugal,6,10-07-02,H,Sporting CP,Moreirense FC,3:00,LW,90+5,3:00,Header,Rui Jorge
2,02/03,Liga Portugal,8,10/26/02,A,Sporting CP,Boavista FC,1:02,NaN,88,1:02,Right-footed shot,Carlos Martins
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,H,Sporting CP,CD Estarreja,4:01,NaN,67,3:00,Left-footed shot,Cesar Prates
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,H,Sporting CP,FC Oliveira do Hospital,8:01,NaN,13,3:00,NaN,NaN
5,03/04,Premier League,11,11-01-03,H,Manchester United,Portsmouth FC,3:00,RW,80,2:00,Direct free kick,NaN
6,03/04,FA Cup,Fifth Round,2/14/04,H,Manchester United,Manchester City,4:02,RW,74,3:00,Right-footed shot,NaN
7,03/04,Premier League,29,3/20/04,H,Manchester United,Tottenham Hotspur,3:00,NaN,89,2:00,Right-footed shot,NaN
8,03/04,Premier League,32,04-10-04,A,Manchester United,Birmingham City,1:02,NaN,60,1:01,Header,Ryan Giggs
9,03/04,Premier League,38,5/15/04,A,Manchester United,Aston Villa,0:02,NaN,4,0:01,Right-footed shot,NaN

# Replace Venue Values

In [8]:
df['Venue']=df['Venue'].replace('H','Home',regex=False)
df['Venue']=df['Venue'].replace('A','Away',regex=False)

In [9]:
df.head(10)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist
0,02/03,Liga Portugal,6,10-07-02,Home,Sporting CP,Moreirense FC,3:00,LW,34,2:00,Solo run,NaN
1,02/03,Liga Portugal,6,10-07-02,Home,Sporting CP,Moreirense FC,3:00,LW,90+5,3:00,Header,Rui Jorge
2,02/03,Liga Portugal,8,10/26/02,Away,Sporting CP,Boavista FC,1:02,NaN,88,1:02,Right-footed shot,Carlos Martins
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,Home,Sporting CP,CD Estarreja,4:01,NaN,67,3:00,Left-footed shot,Cesar Prates
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,Home,Sporting CP,FC Oliveira do Hospital,8:01,NaN,13,3:00,NaN,NaN
5,03/04,Premier League,11,11-01-03,Home,Manchester United,Portsmouth FC,3:00,RW,80,2:00,Direct free kick,NaN
6,03/04,FA Cup,Fifth Round,2/14/04,Home,Manchester United,Manchester City,4:02,RW,74,3:00,Right-footed shot,NaN
7,03/04,Premier League,29,3/20/04,Home,Manchester United,Tottenham Hotspur,3:00,NaN,89,2:00,Right-footed shot,NaN
8,03/04,Premier League,32,04-10-04,Away,Manchester United,Birmingham City,1:02,NaN,60,1:01,Header,Ryan Giggs
9,03/04,Premier League,38,5/15/04,Away,Manchester United,Aston Villa,0:02,NaN,4,0:01,Right-footed shot,NaN

# Viewing Distinct Values In All Columns

In [10]:
df['Season'].unique()

array(['02/03', '03/04', '04/05', '05/06', '06/07', '07/08', '08/09',
       '09/10', '10/11', '11/12', 'Dec-13', '13/14', '14/15', '15/16',
       '16/17', '17/18', '18/19', '19/20', '20/21', '21/22', '22/23'],
      dtype=object)

In [11]:
df['Competition'].unique()

array(['Liga Portugal', 'Taca de Portugal Placard', 'Premier League',
       'FA Cup', 'UEFA Champions League Qualifying', 'EFL Cup',
       'UEFA Champions League', 'FIFA Club World Cup', 'LaLiga',
       'Copa del Rey', 'Supercopa', 'UEFA Super Cup', 'Serie A',
       'Supercoppa Italiana', 'Italy Cup', 'Europa League',
       'Saudi Pro League'], dtype=object)

In [12]:
df['Matchday'].unique()

array(['6', '8', 'Fourth Round', 'Fifth Round', '11', '29', '32', '38',
       'Final', '16', 'Third Round', '24', '25', 'Sixth Round', '30',
       'Semi-Finals', '3rd round', 'Round of 16', '20', '26', '28', '1',
       '10', '15', '17', '19', '21', '23', '6th round', 'Quarter-Finals',
       '37', 'Group Stage', '9', '12', '13', '18', '22', '27', 'last 16',
       '31', '33', '34', '36', '2', '3', '4', '35', '7', '4th round',
       '14', 'final', '5'], dtype=object)

In [13]:
df['Date'].unique()

array(['10-07-02', '10/26/02', '11/24/02', '12/18/02', '11-01-03',
       '2/14/04', '3/20/04', '04-10-04', '5/15/04', '5/22/04', '12-04-04',
       '1/19/05', '1/22/05', '02-01-05', '2/19/05', '03-12-05', '3/19/05',
       '4/17/05', '08-09-05', '10/29/05', '11/30/05', '12/31/05',
       '02-04-06', '02-11-06', '2/26/06', '03-06-06', '05-07-06',
       '8/20/06', '9/23/06', '10/28/06', '11-04-06', '11/29/06',
       '12-09-06', '12/23/06', '12/26/06', '12/30/06', '1/13/07',
       '1/31/07', '02-03-07', '2/24/07', '03-10-07', '3/19/07',
       '04-10-07', '4/14/07', '4/24/07', '05-05-07', '9/19/07', '9/29/07',
       '10-06-07', '10/23/07', '11-03-07', '11-07-07', '11-11-07',
       '11/27/07', '12-03-07', '12-08-07', '12/23/07', '12/26/07',
       '12/29/07', '01-05-08', '01-12-08', '1/19/08', '1/27/08',
       '1/30/08', '2/23/08', '03-04-08', '3/15/08', '3/19/08', '3/23/08',
       '3/29/08', '04-01-08', '04-06-08', '4/13/08', '05-03-08',
       '05-11-08', '5/21/08', '9/23/08', '9/27/08', '10/18/08',
       '10/29/08', '11-01-08', '11/15/08', '12/18/08', '1/20/09',
       '1/27/09', '1/31/09', '2/15/09', '2/21/09', '03-11-09', '3/14/09',
       '04-05-09', '4/15/09', '4/25/09', '05-05-09', '05-10-09',
       '8/29/09', '09-12-09', '9/15/09', '9/20/09', '9/23/09', '9/30/09',
       '12-05-09', '12-08-09', '12/19/09', '1/24/10', '2/13/10',
       '2/21/10', '2/27/10', '03-06-10', '03-10-10', '3/14/10', '3/25/10',
       '04-04-10', '4/15/10', '4/18/10', '05-02-10', '05-05-10',
       '05-08-10', '9/21/10', '10-03-10', '10/16/10', '10/19/10',
       '10/23/10', '10/30/10', '11-10-10', '11/20/10', '11/23/10',
       '12-04-10', '12-08-10', '12-12-10', '12/22/10', '01-03-11',
       '01-09-11', '1/13/11', '1/20/11', '02-06-11', '03-03-11',
       '04-05-11', '04-09-11', '4/13/11', '4/16/11', '4/20/11',
       '05-07-11', '05-10-11', '5/15/11', '5/21/11', '8/17/11', '8/28/11',
       '09-10-11', '9/24/11', '9/27/11', '10/22/11', '11-02-11',
       '11-06-11', '11/19/11', '11/26/11', '12-03-11', '12/13/11',
       '12/17/11', '01-07-12', '1/18/12', '1/22/12', '1/25/12', '1/28/12',
       '02-12-12', '2/18/12', '2/21/12', '2/26/12', '03-04-12',
       '03-10-12', '3/14/12', '3/21/12', '3/24/12', '3/31/12', '04-04-12',
       '04-11-12', '4/14/12', '4/21/12', '4/25/12', '4/29/12', '05-02-12',
       '05-05-12', '5/13/12', '8/23/12', '8/29/12', '09-02-12', '9/18/12',
       '9/24/12', '9/30/12', '10-03-12', '10-07-12', '10/20/12',
       '10/24/12', '10/28/12', '11-11-12', '12-01-12', '12-04-12',
       '12-12-12', '12/16/12', '01-06-13', '01-09-13', '1/20/13',
       '1/27/13', '02-09-13', '2/13/13', '2/26/13', '03-05-13',
       '03-10-13', '3/16/13', '3/30/13', '04-03-13', '04-06-13',
       '04-09-13', '4/14/13', '4/24/13', '05-04-13', '05-08-13',
       '5/17/13', '09-01-13', '9/14/13', '9/17/13', '9/22/13', '9/25/13',
       '10-02-13', '10-05-13', '10/19/13', '10/23/13', '10/30/13',
       '11-02-13', '11-05-13', '11-09-13', '11/23/13', '12-10-13',
       '12/22/13', '01-06-14', '1/15/14', '1/18/14', '1/25/14',
       '02-11-14', '2/26/14', '03-02-14', '03-09-14', '3/15/14',
       '3/18/14', '3/23/14', '3/26/14', '3/29/14', '04-02-14', '4/26/14',
       '4/29/14', '05-04-14', '5/24/14', '08-12-14', '8/25/14', '9/13/14',
       '9/16/14', '9/20/14', '9/23/14', '9/27/14', '10-01-14', '10-05-14',
       '10/18/14', '10/22/14', '10/25/14', '11-01-14', '11-08-14',
       '11/22/14', '11/26/14', '12-06-14', '12-09-14', '12-12-14',
       '01-04-15', '1/15/15', '1/18/15', '2/18/15', '2/22/15', '03-01-15',
       '03-10-15', '3/22/15', '04-05-15', '04-08-15', '04-11-15',
       '4/18/15', '05-02-15', '05-05-15', '5/13/15', '5/17/15', '5/23/15',
       '09-12-15', '9/15/15', '9/30/15', '10/17/15', '10/24/15',
       '10/31/15', '11/25/15', '11/29/15', '12-05-15', '12-08-15',
       '12/20/15', '12/30/15', '1/17/16', '1/31/16', '2/13/16', '2/17/16',
       '2/21/16', '03-02-16', '03-05-16', '03-08-16', '3/20/16',
       '04-02-16', '04-09-16', '04-12-16', '4/16/16', '05-08-16',
       '5/14/16', '09-10-16', '9/14/16', '9/27/16', '10/15/16',
       '10/29/16', '11/19/16', '11/26/16', '12/15/16', '12/18/16',
       '01-07-17', '1/15/17', '1/25/17', '1/29/17', '02-11-17', '2/22/17',
       '2/26/17', '03-01-17', '03-12-17', '04-12-17', '4/18/17',
       '4/29/17', '05-02-17', '5/14/17', '5/17/17', '5/21/17', '06-03-17',
       '8/13/17', '9/13/17', '9/26/17', '10/14/17', '10/17/17',
       '11-01-17', '11/21/17', '11/25/17', '12-06-17', '12-09-17',
       '12/13/17', '12/16/17', '1/21/18', '1/27/18', '02-10-18',
       '2/14/18', '2/18/18', '2/24/18', '03-03-18', '03-06-18',
       '03-10-18', '3/18/18', '04-03-18', '04-08-18', '04-11-18',
       '4/18/18', '05-06-18', '5/19/18', '9/16/18', '9/23/18', '10-06-18',
       '10/20/18', '10/27/18', '11-07-18', '11-11-18', '11/24/18',
       '12-01-18', '12/15/18', '12/26/18', '12/29/18', '1/16/19',
       '1/27/19', '02-02-19', '02-10-19', '2/15/19', '03-12-19',
       '04-10-19', '4/16/19', '4/27/19', '05-03-19', '8/31/19', '9/21/19',
       '9/28/19', '10-01-19', '10/19/19', '10/30/19', '12-01-19',
       '12-07-19', '12-11-19', '12/15/19', '12/18/19', '01-06-20',
       '01-12-20', '1/19/20', '1/22/20', '1/26/20', '02-02-20',
       '02-08-20', '2/13/20', '2/22/20', '6/22/20', '6/26/20', '6/30/20',
       '07-04-20', '07-07-20', '07-11-20', '7/20/20', '7/26/20',
       '08-07-20', '9/20/20', '9/27/20', '11-01-20', '11-08-20',
       '11/21/20', '11/24/20', '12-02-20', '12-08-20', '12/13/20',
       '12/19/20', '01-03-21', '01-10-21', '1/20/21', '02-02-21',
       '02-06-21', '2/22/21', '2/27/21', '03-02-21', '3/14/21',
       '04-03-21', '04-07-21', '05-02-21', '05-12-21', '5/15/21',
       '09-11-21', '9/14/21', '9/19/21', '9/29/21', '10/20/21',
       '10/30/21', '11-02-21', '11/23/21', '12-02-21', '12-11-21',
       '12/30/21', '2/15/22', '03-12-22', '4/16/22', '4/23/22', '4/28/22',
       '05-02-22', '9/15/22', '10/9/22', '10/27/22', '2/3/23', '2/9/23',
       '2/25/23', '3/18/23'], dtype=object)

In [14]:
df['Venue'].unique()

array(['Home', 'Away'], dtype=object)

In [15]:
df['Club'].unique()

array(['Sporting CP', 'Manchester United', 'Real Madrid', 'Juventus FC',
       'Al-Nassr FC'], dtype=object)

In [16]:
df['Opponent'].unique()

array(['Moreirense FC', 'Boavista FC', 'CD Estarreja',
       'FC Oliveira do Hospital', 'Portsmouth FC', 'Manchester City',
       'Tottenham Hotspur', 'Birmingham City', 'Aston Villa',
       'Millwall FC', 'Southampton FC', 'Exeter City', 'Arsenal FC',
       'Everton FC', 'Fulham FC', 'Newcastle United', 'Debreceni VSC',
       'Middlesbrough FC', 'West Bromwich Albion', 'Bolton Wanderers',
       'Wigan Athletic', 'Charlton Athletic', 'Reading FC', 'Watford FC',
       'AS Roma', 'AC Milan', 'Sporting CP', 'Dynamo Kyiv',
       'Blackburn Rovers', 'Derby County', 'Sunderland AFC',
       'West Ham United', 'Olympique Lyon', 'Liverpool FC', 'Chelsea FC',
       'Hull City', 'Stoke City', 'Gamba Osaka', 'FC Internazionale',
       'FC Porto', 'Deportivo de La CoruÃ±a', 'RCD Espanyol Barcelona',
       'FC ZÃ¼rich', 'Xerez CD', 'Villarreal CF', 'Olympique Marseille',
       'UD Almeria', 'Real Zaragoza', 'Malaga CF', 'CD Tenerife',
       'Sevilla FC', 'Real Valladolid CF', 'Getafe CF',
       'Racing Santander', 'Valencia CF', 'CA Osasuna', 'RCD Mallorca',
       'Athletic Bilbao', 'Hercules CF', 'Real Murcia CF',
       'Ajax Amsterdam', 'AJ Auxerre', 'Levante UD', 'Atletico de Madrid',
       'Real Sociedad', 'FC Barcelona', 'Rayo Vallecano',
       'Sporting GijÃ³n', 'SD Ponferradina', 'Granada CF', 'CSKA Moscow',
       'Real Betis Balompie', 'APOEL Nicosia', 'Bayern Munich',
       'Celta de Vigo', 'Borussia Dortmund', 'Manchester United',
       'Galatasaray', 'Elche CF', 'FC Copenhagen', 'Juventus FC',
       'FC Schalke 04', 'CÃ³rdoba CF', 'FC Basel 1893',
       'Ludogorets Razgrad', 'SD Eibar', 'Shakhtar Donetsk', 'MalmÃ¶ FF',
       'UD Las Palmas', 'VfL Wolfsburg', 'Deportivo Alaves', 'CF America',
       'Kashima Antlers', 'Al-Jazira (Abu Dhabi)',
       'GrÃªmio Foot-Ball Porto Alegrense', 'Paris Saint-Germain',
       'Girona FC', 'US Sassuolo', 'Frosinone Calcio', 'Udinese Calcio',
       'Genoa CFC', 'Empoli FC ', 'SPAL', 'ACF Fiorentina', 'Torino FC',
       'Atalanta BC', 'UC Sampdoria', 'SS Lazio', 'Parma Calcio 1913',
       'Inter Milan', 'SSC Napoli', 'Hellas Verona',
       'Bayer 04 Leverkusen', 'Bologna FC 1909', 'Cagliari Calcio',
       'US Lecce', 'Spezia Calcio', 'Ferencvarosi TC', 'FC Crotone',
       'BSC Young Boys', 'Norwich City', 'Burnley FC',
       'Brighton & Hove Albion', 'Brentford FC', 'FC Sheriff', 'Al-Fateh',
       'Al-Wehda FC', 'Damac FC', 'Abha Club'], dtype=object)

In [17]:
df['Result'].unique()

array(['3:00', '1:02', '4:01', '8:01', '4:02', '0:02', '3:01', '2:04',
       '0:04', '1:00', '1:04', '1:03', '4:00', '5:01', '1:01', '0:03',
       '3:02', '2:02', '7:01', '0:01', '2:00', '2:01', '6:00', '1:05',
       '6:5 on pens', '4:03', '5:00', '3:05', '0:05', '5:02', '2:05',
       '6:02', '6:01', '8:00', '2:03', '7:00', '0:1 AET', '2:06', '0:06',
       '3:4 on pens', '2:1 AET', '1:06', '7:03', '3:04', '4:1 AET',
       '2:08', '9:01', '10:02', '4:2 AET', '3:03', '6:03', '1:2', '3:0',
       '2:2', '0:4', '0:3', '2:1'], dtype=object)

In [18]:
df['Playing_Position'].unique()

array(['LW', nan, 'RW', 'CF', 'LW ', 'CF '], dtype=object)

In [19]:
df['Playing_Position']=df['Playing_Position'].dropna()

In [20]:
df['Playing_Position'].unique()

array(['LW', nan, 'RW', 'CF', 'LW ', 'CF '], dtype=object)

In [21]:
df['Playing_Position'] = df['Playing_Position'].replace('nan','')

In [22]:
df['Playing_Position']=df['Playing_Position'].fillna('Unknown')

In [23]:
df['Playing_Position'].unique()

array(['LW', 'Unknown', 'RW', 'CF', 'LW ', 'CF '], dtype=object)

In [24]:
df['Minute'].unique()

array(['34', '90+5', '88', '67', '13', '80', '74', '89', '60', '4', '44',
       '87', '9', '8', '54', '58', '45+1', '21', '76', '63', '90', '12',
       '68', '14', '38', '45', '59', '23', '19', '73', '82', '10', '39',
       '84', '85', '47', '50', '77', '49', '28', '5', '62', '51', '41',
       '35', '90+3', '22', '81', '48', '70', '90+2', '69', '56', '79',
       '16', '53', '3', '24', '32', '26', '25', '30', '43', '65', '11',
       '6', '57', '61', '17', '27', '1', '75', '2', '64', '71', '18',
       '78', '29', '36', '15', '55', '86', '90+1', '72', '20', '42',
       '103', '46', '52', '90+4', '37', '66', '90+6', '31', '40', '120',
       '83', '7', '33', '97', '104', '105', '109', '90+7', '45+7', '45+2'],
      dtype=object)

In [25]:
df[['Minute','Extra Minute']]=df['Minute'].str.split('+',n=1,expand=True)

In [26]:
df.head(10)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist,Extra Minute
0,02/03,Liga Portugal,6,10-07-02,Home,Sporting CP,Moreirense FC,3:00,LW,34,2:00,Solo run,NaN,None
1,02/03,Liga Portugal,6,10-07-02,Home,Sporting CP,Moreirense FC,3:00,LW,90,3:00,Header,Rui Jorge,5
2,02/03,Liga Portugal,8,10/26/02,Away,Sporting CP,Boavista FC,1:02,Unknown,88,1:02,Right-footed shot,Carlos Martins,None
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,Home,Sporting CP,CD Estarreja,4:01,Unknown,67,3:00,Left-footed shot,Cesar Prates,None
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,Home,Sporting CP,FC Oliveira do Hospital,8:01,Unknown,13,3:00,NaN,NaN,None
5,03/04,Premier League,11,11-01-03,Home,Manchester United,Portsmouth FC,3:00,RW,80,2:00,Direct free kick,NaN,None
6,03/04,FA Cup,Fifth Round,2/14/04,Home,Manchester United,Manchester City,4:02,RW,74,3:00,Right-footed shot,NaN,None
7,03/04,Premier League,29,3/20/04,Home,Manchester United,Tottenham Hotspur,3:00,Unknown,89,2:00,Right-footed shot,NaN,None
8,03/04,Premier League,32,04-10-04,Away,Manchester United,Birmingham City,1:02,Unknown,60,1:01,Header,Ryan Giggs,None
9,03/04,Premier League,38,5/15/04,Away,Manchester United,Aston Villa,0:02,Unknown,4,0:01,Right-footed shot,NaN,None

In [27]:
df['Minute'] = pd.to_numeric(df['Minute'])

In [28]:
df['Extra Minute'] = pd.to_numeric(df['Extra Minute'])

In [29]:
df.head(10)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist,Extra Minute
0,02/03,Liga Portugal,6,10-07-02,Home,Sporting CP,Moreirense FC,3:00,LW,34,2:00,Solo run,NaN,NaN
1,02/03,Liga Portugal,6,10-07-02,Home,Sporting CP,Moreirense FC,3:00,LW,90,3:00,Header,Rui Jorge,5.0
2,02/03,Liga Portugal,8,10/26/02,Away,Sporting CP,Boavista FC,1:02,Unknown,88,1:02,Right-footed shot,Carlos Martins,NaN
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,Home,Sporting CP,CD Estarreja,4:01,Unknown,67,3:00,Left-footed shot,Cesar Prates,NaN
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,Home,Sporting CP,FC Oliveira do Hospital,8:01,Unknown,13,3:00,NaN,NaN,NaN
5,03/04,Premier League,11,11-01-03,Home,Manchester United,Portsmouth FC,3:00,RW,80,2:00,Direct free kick,NaN,NaN
6,03/04,FA Cup,Fifth Round,2/14/04,Home,Manchester United,Manchester City,4:02,RW,74,3:00,Right-footed shot,NaN,NaN
7,03/04,Premier League,29,3/20/04,Home,Manchester United,Tottenham Hotspur,3:00,Unknown,89,2:00,Right-footed shot,NaN,NaN
8,03/04,Premier League,32,04-10-04,Away,Manchester United,Birmingham City,1:02,Unknown,60,1:01,Header,Ryan Giggs,NaN
9,03/04,Premier League,38,5/15/04,Away,Manchester United,Aston Villa,0:02,Unknown,4,0:01,Right-footed shot,NaN,NaN

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Season            710 non-null    object
 1   Competition       710 non-null    object
 2   Matchday          710 non-null    object
 3   Date              710 non-null    object
 4   Venue             710 non-null    object
 5   Club              710 non-null    object
 6   Opponent          710 non-null    object
 7   Result            710 non-null    object
 8   Playing_Position  710 non-null    object
 9   Minute            710 non-null    int64
 10  At_score          710 non-null    object
 11  Type              695 non-null    object
 12  Goal_assist       464 non-null    object
 13  Extra Minute      29 non-null     float64
dtypes: float64(1), int64(1), object(12)
memory usage: 77.8+ KB

In [31]:
df['Extra Minute'] = df['Extra Minute'].fillna(0)

In [32]:
df['Total_Minutes_Match_Played']=df['Minute']+df['Extra Minute']

In [33]:
df.head()

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Minute,At_score,Type,Goal_assist,Extra Minute,Total_Minutes_Match_Played
0,02/03,Liga Portugal,6,10-07-02,Home,Sporting CP,Moreirense FC,3:00,LW,34,2:00,Solo run,NaN,0.0,34.0
1,02/03,Liga Portugal,6,10-07-02,Home,Sporting CP,Moreirense FC,3:00,LW,90,3:00,Header,Rui Jorge,5.0,95.0
2,02/03,Liga Portugal,8,10/26/02,Away,Sporting CP,Boavista FC,1:02,Unknown,88,1:02,Right-footed shot,Carlos Martins,0.0,88.0
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,Home,Sporting CP,CD Estarreja,4:01,Unknown,67,3:00,Left-footed shot,Cesar Prates,0.0,67.0
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,Home,Sporting CP,FC Oliveira do Hospital,8:01,Unknown,13,3:00,NaN,NaN,0.0,13.0

In [34]:
df = df.drop(columns='Minute')

In [35]:
df=df.drop(columns='Extra Minute')

In [36]:
df.head(10)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,At_score,Type,Goal_assist,Total_Minutes_Match_Played
0,02/03,Liga Portugal,6,10-07-02,Home,Sporting CP,Moreirense FC,3:00,LW,2:00,Solo run,NaN,34.0
1,02/03,Liga Portugal,6,10-07-02,Home,Sporting CP,Moreirense FC,3:00,LW,3:00,Header,Rui Jorge,95.0
2,02/03,Liga Portugal,8,10/26/02,Away,Sporting CP,Boavista FC,1:02,Unknown,1:02,Right-footed shot,Carlos Martins,88.0
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,Home,Sporting CP,CD Estarreja,4:01,Unknown,3:00,Left-footed shot,Cesar Prates,67.0
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,Home,Sporting CP,FC Oliveira do Hospital,8:01,Unknown,3:00,NaN,NaN,13.0
5,03/04,Premier League,11,11-01-03,Home,Manchester United,Portsmouth FC,3:00,RW,2:00,Direct free kick,NaN,80.0
6,03/04,FA Cup,Fifth Round,2/14/04,Home,Manchester United,Manchester City,4:02,RW,3:00,Right-footed shot,NaN,74.0
7,03/04,Premier League,29,3/20/04,Home,Manchester United,Tottenham Hotspur,3:00,Unknown,2:00,Right-footed shot,NaN,89.0
8,03/04,Premier League,32,04-10-04,Away,Manchester United,Birmingham City,1:02,Unknown,1:01,Header,Ryan Giggs,60.0
9,03/04,Premier League,38,5/15/04,Away,Manchester United,Aston Villa,0:02,Unknown,0:01,Right-footed shot,NaN,4.0

In [37]:
df['Date'].unique()

array(['10-07-02', '10/26/02', '11/24/02', '12/18/02', '11-01-03',
       '2/14/04', '3/20/04', '04-10-04', '5/15/04', '5/22/04', '12-04-04',
       '1/19/05', '1/22/05', '02-01-05', '2/19/05', '03-12-05', '3/19/05',
       '4/17/05', '08-09-05', '10/29/05', '11/30/05', '12/31/05',
       '02-04-06', '02-11-06', '2/26/06', '03-06-06', '05-07-06',
       '8/20/06', '9/23/06', '10/28/06', '11-04-06', '11/29/06',
       '12-09-06', '12/23/06', '12/26/06', '12/30/06', '1/13/07',
       '1/31/07', '02-03-07', '2/24/07', '03-10-07', '3/19/07',
       '04-10-07', '4/14/07', '4/24/07', '05-05-07', '9/19/07', '9/29/07',
       '10-06-07', '10/23/07', '11-03-07', '11-07-07', '11-11-07',
       '11/27/07', '12-03-07', '12-08-07', '12/23/07', '12/26/07',
       '12/29/07', '01-05-08', '01-12-08', '1/19/08', '1/27/08',
       '1/30/08', '2/23/08', '03-04-08', '3/15/08', '3/19/08', '3/23/08',
       '3/29/08', '04-01-08', '04-06-08', '4/13/08', '05-03-08',
       '05-11-08', '5/21/08', '9/23/08', '9/27/08', '10/18/08',
       '10/29/08', '11-01-08', '11/15/08', '12/18/08', '1/20/09',
       '1/27/09', '1/31/09', '2/15/09', '2/21/09', '03-11-09', '3/14/09',
       '04-05-09', '4/15/09', '4/25/09', '05-05-09', '05-10-09',
       '8/29/09', '09-12-09', '9/15/09', '9/20/09', '9/23/09', '9/30/09',
       '12-05-09', '12-08-09', '12/19/09', '1/24/10', '2/13/10',
       '2/21/10', '2/27/10', '03-06-10', '03-10-10', '3/14/10', '3/25/10',
       '04-04-10', '4/15/10', '4/18/10', '05-02-10', '05-05-10',
       '05-08-10', '9/21/10', '10-03-10', '10/16/10', '10/19/10',
       '10/23/10', '10/30/10', '11-10-10', '11/20/10', '11/23/10',
       '12-04-10', '12-08-10', '12-12-10', '12/22/10', '01-03-11',
       '01-09-11', '1/13/11', '1/20/11', '02-06-11', '03-03-11',
       '04-05-11', '04-09-11', '4/13/11', '4/16/11', '4/20/11',
       '05-07-11', '05-10-11', '5/15/11', '5/21/11', '8/17/11', '8/28/11',
       '09-10-11', '9/24/11', '9/27/11', '10/22/11', '11-02-11',
       '11-06-11', '11/19/11', '11/26/11', '12-03-11', '12/13/11',
       '12/17/11', '01-07-12', '1/18/12', '1/22/12', '1/25/12', '1/28/12',
       '02-12-12', '2/18/12', '2/21/12', '2/26/12', '03-04-12',
       '03-10-12', '3/14/12', '3/21/12', '3/24/12', '3/31/12', '04-04-12',
       '04-11-12', '4/14/12', '4/21/12', '4/25/12', '4/29/12', '05-02-12',
       '05-05-12', '5/13/12', '8/23/12', '8/29/12', '09-02-12', '9/18/12',
       '9/24/12', '9/30/12', '10-03-12', '10-07-12', '10/20/12',
       '10/24/12', '10/28/12', '11-11-12', '12-01-12', '12-04-12',
       '12-12-12', '12/16/12', '01-06-13', '01-09-13', '1/20/13',
       '1/27/13', '02-09-13', '2/13/13', '2/26/13', '03-05-13',
       '03-10-13', '3/16/13', '3/30/13', '04-03-13', '04-06-13',
       '04-09-13', '4/14/13', '4/24/13', '05-04-13', '05-08-13',
       '5/17/13', '09-01-13', '9/14/13', '9/17/13', '9/22/13', '9/25/13',
       '10-02-13', '10-05-13', '10/19/13', '10/23/13', '10/30/13',
       '11-02-13', '11-05-13', '11-09-13', '11/23/13', '12-10-13',
       '12/22/13', '01-06-14', '1/15/14', '1/18/14', '1/25/14',
       '02-11-14', '2/26/14', '03-02-14', '03-09-14', '3/15/14',
       '3/18/14', '3/23/14', '3/26/14', '3/29/14', '04-02-14', '4/26/14',
       '4/29/14', '05-04-14', '5/24/14', '08-12-14', '8/25/14', '9/13/14',
       '9/16/14', '9/20/14', '9/23/14', '9/27/14', '10-01-14', '10-05-14',
       '10/18/14', '10/22/14', '10/25/14', '11-01-14', '11-08-14',
       '11/22/14', '11/26/14', '12-06-14', '12-09-14', '12-12-14',
       '01-04-15', '1/15/15', '1/18/15', '2/18/15', '2/22/15', '03-01-15',
       '03-10-15', '3/22/15', '04-05-15', '04-08-15', '04-11-15',
       '4/18/15', '05-02-15', '05-05-15', '5/13/15', '5/17/15', '5/23/15',
       '09-12-15', '9/15/15', '9/30/15', '10/17/15', '10/24/15',
       '10/31/15', '11/25/15', '11/29/15', '12-05-15', '12-08-15',
       '12/20/15', '12/30/15', '1/17/16', '1/31/16', '2/13/16', '2/17/16',
       '2/21/16', '03-02-16', '03-05-16', '03-08-16', '3/20/16',
       '04-02-16', '04-09-16', '04-12-16', '4/16/16', '05-08-16',
       '5/14/16', '09-10-16', '9/14/16', '9/27/16', '10/15/16',
       '10/29/16', '11/19/16', '11/26/16', '12/15/16', '12/18/16',
       '01-07-17', '1/15/17', '1/25/17', '1/29/17', '02-11-17', '2/22/17',
       '2/26/17', '03-01-17', '03-12-17', '04-12-17', '4/18/17',
       '4/29/17', '05-02-17', '5/14/17', '5/17/17', '5/21/17', '06-03-17',
       '8/13/17', '9/13/17', '9/26/17', '10/14/17', '10/17/17',
       '11-01-17', '11/21/17', '11/25/17', '12-06-17', '12-09-17',
       '12/13/17', '12/16/17', '1/21/18', '1/27/18', '02-10-18',
       '2/14/18', '2/18/18', '2/24/18', '03-03-18', '03-06-18',
       '03-10-18', '3/18/18', '04-03-18', '04-08-18', '04-11-18',
       '4/18/18', '05-06-18', '5/19/18', '9/16/18', '9/23/18', '10-06-18',
       '10/20/18', '10/27/18', '11-07-18', '11-11-18', '11/24/18',
       '12-01-18', '12/15/18', '12/26/18', '12/29/18', '1/16/19',
       '1/27/19', '02-02-19', '02-10-19', '2/15/19', '03-12-19',
       '04-10-19', '4/16/19', '4/27/19', '05-03-19', '8/31/19', '9/21/19',
       '9/28/19', '10-01-19', '10/19/19', '10/30/19', '12-01-19',
       '12-07-19', '12-11-19', '12/15/19', '12/18/19', '01-06-20',
       '01-12-20', '1/19/20', '1/22/20', '1/26/20', '02-02-20',
       '02-08-20', '2/13/20', '2/22/20', '6/22/20', '6/26/20', '6/30/20',
       '07-04-20', '07-07-20', '07-11-20', '7/20/20', '7/26/20',
       '08-07-20', '9/20/20', '9/27/20', '11-01-20', '11-08-20',
       '11/21/20', '11/24/20', '12-02-20', '12-08-20', '12/13/20',
       '12/19/20', '01-03-21', '01-10-21', '1/20/21', '02-02-21',
       '02-06-21', '2/22/21', '2/27/21', '03-02-21', '3/14/21',
       '04-03-21', '04-07-21', '05-02-21', '05-12-21', '5/15/21',
       '09-11-21', '9/14/21', '9/19/21', '9/29/21', '10/20/21',
       '10/30/21', '11-02-21', '11/23/21', '12-02-21', '12-11-21',
       '12/30/21', '2/15/22', '03-12-22', '4/16/22', '4/23/22', '4/28/22',
       '05-02-22', '9/15/22', '10/9/22', '10/27/22', '2/3/23', '2/9/23',
       '2/25/23', '3/18/23'], dtype=object)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Season                      710 non-null    object
 1   Competition                 710 non-null    object
 2   Matchday                    710 non-null    object
 3   Date                        710 non-null    object
 4   Venue                       710 non-null    object
 5   Club                        710 non-null    object
 6   Opponent                    710 non-null    object
 7   Result                      710 non-null    object
 8   Playing_Position            710 non-null    object
 9   At_score                    710 non-null    object
 10  Type                        695 non-null    object
 11  Goal_assist                 464 non-null    object
 12  Total_Minutes_Match_Played  710 non-null    float64
dtypes: float64(1), object(12)
memory usage: 72.2+ KB

In [39]:
df['Date'].head(50)

0     10-07-02
1     10-07-02
2     10/26/02
3     11/24/02
4     12/18/02
5     11-01-03
6      2/14/04
7      3/20/04
8     04-10-04
9      5/15/04
10     5/22/04
11    12-04-04
12     1/19/05
13     1/22/05
14    02-01-05
15    02-01-05
16     2/19/05
17    03-12-05
18     3/19/05
19     4/17/05
20    08-09-05
21    10/29/05
22    11/30/05
23    12/31/05
24    12/31/05
25    02-04-06
26    02-04-06
27    02-11-06
28    02-11-06
29     2/26/06
30    03-06-06
31    05-07-06
32     8/20/06
33     9/23/06
34    10/28/06
35    11-04-06
36    11/29/06
37    12-09-06
38    12/23/06
39    12/23/06
40    12/26/06
41    12/26/06
42    12/30/06
43    12/30/06
44     1/13/07
45     1/31/07
46    02-03-07
47     2/24/07
48    03-10-07
49     3/19/07
Name: Date, dtype: object

In [40]:
df['Date']=df['Date'].replace('[^0-9]','/',regex=True)

In [41]:
df['Date'].unique()

array(['10/07/02', '10/26/02', '11/24/02', '12/18/02', '11/01/03',
       '2/14/04', '3/20/04', '04/10/04', '5/15/04', '5/22/04', '12/04/04',
       '1/19/05', '1/22/05', '02/01/05', '2/19/05', '03/12/05', '3/19/05',
       '4/17/05', '08/09/05', '10/29/05', '11/30/05', '12/31/05',
       '02/04/06', '02/11/06', '2/26/06', '03/06/06', '05/07/06',
       '8/20/06', '9/23/06', '10/28/06', '11/04/06', '11/29/06',
       '12/09/06', '12/23/06', '12/26/06', '12/30/06', '1/13/07',
       '1/31/07', '02/03/07', '2/24/07', '03/10/07', '3/19/07',
       '04/10/07', '4/14/07', '4/24/07', '05/05/07', '9/19/07', '9/29/07',
       '10/06/07', '10/23/07', '11/03/07', '11/07/07', '11/11/07',
       '11/27/07', '12/03/07', '12/08/07', '12/23/07', '12/26/07',
       '12/29/07', '01/05/08', '01/12/08', '1/19/08', '1/27/08',
       '1/30/08', '2/23/08', '03/04/08', '3/15/08', '3/19/08', '3/23/08',
       '3/29/08', '04/01/08', '04/06/08', '4/13/08', '05/03/08',
       '05/11/08', '5/21/08', '9/23/08', '9/27/08', '10/18/08',
       '10/29/08', '11/01/08', '11/15/08', '12/18/08', '1/20/09',
       '1/27/09', '1/31/09', '2/15/09', '2/21/09', '03/11/09', '3/14/09',
       '04/05/09', '4/15/09', '4/25/09', '05/05/09', '05/10/09',
       '8/29/09', '09/12/09', '9/15/09', '9/20/09', '9/23/09', '9/30/09',
       '12/05/09', '12/08/09', '12/19/09', '1/24/10', '2/13/10',
       '2/21/10', '2/27/10', '03/06/10', '03/10/10', '3/14/10', '3/25/10',
       '04/04/10', '4/15/10', '4/18/10', '05/02/10', '05/05/10',
       '05/08/10', '9/21/10', '10/03/10', '10/16/10', '10/19/10',
       '10/23/10', '10/30/10', '11/10/10', '11/20/10', '11/23/10',
       '12/04/10', '12/08/10', '12/12/10', '12/22/10', '01/03/11',
       '01/09/11', '1/13/11', '1/20/11', '02/06/11', '03/03/11',
       '04/05/11', '04/09/11', '4/13/11', '4/16/11', '4/20/11',
       '05/07/11', '05/10/11', '5/15/11', '5/21/11', '8/17/11', '8/28/11',
       '09/10/11', '9/24/11', '9/27/11', '10/22/11', '11/02/11',
       '11/06/11', '11/19/11', '11/26/11', '12/03/11', '12/13/11',
       '12/17/11', '01/07/12', '1/18/12', '1/22/12', '1/25/12', '1/28/12',
       '02/12/12', '2/18/12', '2/21/12', '2/26/12', '03/04/12',
       '03/10/12', '3/14/12', '3/21/12', '3/24/12', '3/31/12', '04/04/12',
       '04/11/12', '4/14/12', '4/21/12', '4/25/12', '4/29/12', '05/02/12',
       '05/05/12', '5/13/12', '8/23/12', '8/29/12', '09/02/12', '9/18/12',
       '9/24/12', '9/30/12', '10/03/12', '10/07/12', '10/20/12',
       '10/24/12', '10/28/12', '11/11/12', '12/01/12', '12/04/12',
       '12/12/12', '12/16/12', '01/06/13', '01/09/13', '1/20/13',
       '1/27/13', '02/09/13', '2/13/13', '2/26/13', '03/05/13',
       '03/10/13', '3/16/13', '3/30/13', '04/03/13', '04/06/13',
       '04/09/13', '4/14/13', '4/24/13', '05/04/13', '05/08/13',
       '5/17/13', '09/01/13', '9/14/13', '9/17/13', '9/22/13', '9/25/13',
       '10/02/13', '10/05/13', '10/19/13', '10/23/13', '10/30/13',
       '11/02/13', '11/05/13', '11/09/13', '11/23/13', '12/10/13',
       '12/22/13', '01/06/14', '1/15/14', '1/18/14', '1/25/14',
       '02/11/14', '2/26/14', '03/02/14', '03/09/14', '3/15/14',
       '3/18/14', '3/23/14', '3/26/14', '3/29/14', '04/02/14', '4/26/14',
       '4/29/14', '05/04/14', '5/24/14', '08/12/14', '8/25/14', '9/13/14',
       '9/16/14', '9/20/14', '9/23/14', '9/27/14', '10/01/14', '10/05/14',
       '10/18/14', '10/22/14', '10/25/14', '11/01/14', '11/08/14',
       '11/22/14', '11/26/14', '12/06/14', '12/09/14', '12/12/14',
       '01/04/15', '1/15/15', '1/18/15', '2/18/15', '2/22/15', '03/01/15',
       '03/10/15', '3/22/15', '04/05/15', '04/08/15', '04/11/15',
       '4/18/15', '05/02/15', '05/05/15', '5/13/15', '5/17/15', '5/23/15',
       '09/12/15', '9/15/15', '9/30/15', '10/17/15', '10/24/15',
       '10/31/15', '11/25/15', '11/29/15', '12/05/15', '12/08/15',
       '12/20/15', '12/30/15', '1/17/16', '1/31/16', '2/13/16', '2/17/16',
       '2/21/16', '03/02/16', '03/05/16', '03/08/16', '3/20/16',
       '04/02/16', '04/09/16', '04/12/16', '4/16/16', '05/08/16',
       '5/14/16', '09/10/16', '9/14/16', '9/27/16', '10/15/16',
       '10/29/16', '11/19/16', '11/26/16', '12/15/16', '12/18/16',
       '01/07/17', '1/15/17', '1/25/17', '1/29/17', '02/11/17', '2/22/17',
       '2/26/17', '03/01/17', '03/12/17', '04/12/17', '4/18/17',
       '4/29/17', '05/02/17', '5/14/17', '5/17/17', '5/21/17', '06/03/17',
       '8/13/17', '9/13/17', '9/26/17', '10/14/17', '10/17/17',
       '11/01/17', '11/21/17', '11/25/17', '12/06/17', '12/09/17',
       '12/13/17', '12/16/17', '1/21/18', '1/27/18', '02/10/18',
       '2/14/18', '2/18/18', '2/24/18', '03/03/18', '03/06/18',
       '03/10/18', '3/18/18', '04/03/18', '04/08/18', '04/11/18',
       '4/18/18', '05/06/18', '5/19/18', '9/16/18', '9/23/18', '10/06/18',
       '10/20/18', '10/27/18', '11/07/18', '11/11/18', '11/24/18',
       '12/01/18', '12/15/18', '12/26/18', '12/29/18', '1/16/19',
       '1/27/19', '02/02/19', '02/10/19', '2/15/19', '03/12/19',
       '04/10/19', '4/16/19', '4/27/19', '05/03/19', '8/31/19', '9/21/19',
       '9/28/19', '10/01/19', '10/19/19', '10/30/19', '12/01/19',
       '12/07/19', '12/11/19', '12/15/19', '12/18/19', '01/06/20',
       '01/12/20', '1/19/20', '1/22/20', '1/26/20', '02/02/20',
       '02/08/20', '2/13/20', '2/22/20', '6/22/20', '6/26/20', '6/30/20',
       '07/04/20', '07/07/20', '07/11/20', '7/20/20', '7/26/20',
       '08/07/20', '9/20/20', '9/27/20', '11/01/20', '11/08/20',
       '11/21/20', '11/24/20', '12/02/20', '12/08/20', '12/13/20',
       '12/19/20', '01/03/21', '01/10/21', '1/20/21', '02/02/21',
       '02/06/21', '2/22/21', '2/27/21', '03/02/21', '3/14/21',
       '04/03/21', '04/07/21', '05/02/21', '05/12/21', '5/15/21',
       '09/11/21', '9/14/21', '9/19/21', '9/29/21', '10/20/21',
       '10/30/21', '11/02/21', '11/23/21', '12/02/21', '12/11/21',
       '12/30/21', '2/15/22', '03/12/22', '4/16/22', '4/23/22', '4/28/22',
       '05/02/22', '9/15/22', '10/9/22', '10/27/22', '2/3/23', '2/9/23',
       '2/25/23', '3/18/23'], dtype=object)

In [42]:
df.head(10)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,At_score,Type,Goal_assist,Total_Minutes_Match_Played
0,02/03,Liga Portugal,6,10/07/02,Home,Sporting CP,Moreirense FC,3:00,LW,2:00,Solo run,NaN,34.0
1,02/03,Liga Portugal,6,10/07/02,Home,Sporting CP,Moreirense FC,3:00,LW,3:00,Header,Rui Jorge,95.0
2,02/03,Liga Portugal,8,10/26/02,Away,Sporting CP,Boavista FC,1:02,Unknown,1:02,Right-footed shot,Carlos Martins,88.0
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,Home,Sporting CP,CD Estarreja,4:01,Unknown,3:00,Left-footed shot,Cesar Prates,67.0
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,Home,Sporting CP,FC Oliveira do Hospital,8:01,Unknown,3:00,NaN,NaN,13.0
5,03/04,Premier League,11,11/01/03,Home,Manchester United,Portsmouth FC,3:00,RW,2:00,Direct free kick,NaN,80.0
6,03/04,FA Cup,Fifth Round,2/14/04,Home,Manchester United,Manchester City,4:02,RW,3:00,Right-footed shot,NaN,74.0
7,03/04,Premier League,29,3/20/04,Home,Manchester United,Tottenham Hotspur,3:00,Unknown,2:00,Right-footed shot,NaN,89.0
8,03/04,Premier League,32,04/10/04,Away,Manchester United,Birmingham City,1:02,Unknown,1:01,Header,Ryan Giggs,60.0
9,03/04,Premier League,38,5/15/04,Away,Manchester United,Aston Villa,0:02,Unknown,0:01,Right-footed shot,NaN,4.0

In [43]:
df['Goal_assist'].unique()

array([nan, 'Rui Jorge', 'Carlos Martins', 'Cesar Prates', 'Ryan Giggs',
       'Gary Neville', 'Paul Scholes', 'Louis Saha',
       'Ruud van Nistelrooy', 'Roy Keane', 'Wayne Rooney', 'John OShea',
       'Ji-sung Park', 'Ole Gunnar Solskjaer', 'Michael Carrick',
       'Wes Brown', 'Patrice Evra', 'Carlos Tevez', 'Nemanja Vidicâ€Ž',
       'Nani', 'Edwin van der Sar', 'Owen Hargreaves', 'Dimitar Berbatov',
       'Anderson', 'Guti', 'Esteban Granero', 'Pepe', 'Karim Benzema',
       'Gonzalo Higuain', 'Lassana Diarra', 'Ezequiel Garay', 'Kaka',
       'Marcelo', 'Sergio Ramos', 'Mesut Ozil', 'Xabi Alonso',
       'Angel Di Maria', 'Sergio Canales', 'Sami Khedira',
       'alvaro Arbeloa', 'Fabio CoentrÃ£o', 'Jose CallejÃ³n',
       'Luka Modric', 'Isco', 'Gareth Bale', 'Daniel Carvajal',
       'James Rodriguez', 'Toni Kroos', 'Chicharito', 'Lucas Vazquez',
       'Danilo', 'Jese', 'alvaro Morata', 'Nacho Fernandez',
       'Mateo Kovacic', 'Marco Asensio', 'Casemiro', 'Borja Mayoral',
       'Emre Can', 'Mario Mandzukic', 'Blaise Matuidi',
       'Leonardo Bonucci', 'Miralem Pjanic', 'Giorgio Chiellini',
       'Paulo Dybala', 'Federico Bernardeschi', 'JoÃ£o Cancelo',
       'Leonardo Spinazzola', 'Douglas Costa', 'Rodrigo Bentancur',
       'Alex Sandro', 'Juan Cuadrado', 'Aaron Ramsey', 'Merih Demiral',
       'Federico Chiesa', 'Adrien Rabiot', 'Luke Shaw', 'Bruno Fernandes',
       'Jesse Lingard', 'Mason Greenwood', 'Marcus Rashford',
       'Scott McTominay', 'Fred', 'Jadon Sancho', 'Alex Telles',
       'Anthony Elanga', 'Nemanja MatiÄ‡', 'Abdulrahman Ghareeb',
       'Sami Al-Najei', '\t', 'Sultan Al-Ghannam', 'Ayman Yahya'],
      dtype=object)

In [44]:
df['Goal_assist']=df['Goal_assist'].fillna('Not Avaliable').str.strip()

In [45]:
df.head(5)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,At_score,Type,Goal_assist,Total_Minutes_Match_Played
0,02/03,Liga Portugal,6,10/07/02,Home,Sporting CP,Moreirense FC,3:00,LW,2:00,Solo run,Not Avaliable,34.0
1,02/03,Liga Portugal,6,10/07/02,Home,Sporting CP,Moreirense FC,3:00,LW,3:00,Header,Rui Jorge,95.0
2,02/03,Liga Portugal,8,10/26/02,Away,Sporting CP,Boavista FC,1:02,Unknown,1:02,Right-footed shot,Carlos Martins,88.0
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,Home,Sporting CP,CD Estarreja,4:01,Unknown,3:00,Left-footed shot,Cesar Prates,67.0
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,Home,Sporting CP,FC Oliveira do Hospital,8:01,Unknown,3:00,NaN,Not Avaliable,13.0

In [46]:
df = df.drop(columns='At_score')

In [47]:
df.head(5)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Type,Goal_assist,Total_Minutes_Match_Played
0,02/03,Liga Portugal,6,10/07/02,Home,Sporting CP,Moreirense FC,3:00,LW,Solo run,Not Avaliable,34.0
1,02/03,Liga Portugal,6,10/07/02,Home,Sporting CP,Moreirense FC,3:00,LW,Header,Rui Jorge,95.0
2,02/03,Liga Portugal,8,10/26/02,Away,Sporting CP,Boavista FC,1:02,Unknown,Right-footed shot,Carlos Martins,88.0
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,Home,Sporting CP,CD Estarreja,4:01,Unknown,Left-footed shot,Cesar Prates,67.0
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,Home,Sporting CP,FC Oliveira do Hospital,8:01,Unknown,NaN,Not Avaliable,13.0

In [48]:
df[['Ronaldo Team Goals','Opponent Team Goals']] = df['Result'].str.split(':',n=1,expand=True)

In [49]:
df.head(5)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Type,Goal_assist,Total_Minutes_Match_Played,Ronaldo Team Goals,Opponent Team Goals
0,02/03,Liga Portugal,6,10/07/02,Home,Sporting CP,Moreirense FC,3:00,LW,Solo run,Not Avaliable,34.0,3,00
1,02/03,Liga Portugal,6,10/07/02,Home,Sporting CP,Moreirense FC,3:00,LW,Header,Rui Jorge,95.0,3,00
2,02/03,Liga Portugal,8,10/26/02,Away,Sporting CP,Boavista FC,1:02,Unknown,Right-footed shot,Carlos Martins,88.0,1,02
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,Home,Sporting CP,CD Estarreja,4:01,Unknown,Left-footed shot,Cesar Prates,67.0,4,01
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,Home,Sporting CP,FC Oliveira do Hospital,8:01,Unknown,NaN,Not Avaliable,13.0,8,01

In [50]:
df['Season'].count()

np.int64(710)

In [51]:
df.head(10)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Result,Playing_Position,Type,Goal_assist,Total_Minutes_Match_Played,Ronaldo Team Goals,Opponent Team Goals
0,02/03,Liga Portugal,6,10/07/02,Home,Sporting CP,Moreirense FC,3:00,LW,Solo run,Not Avaliable,34.0,3,00
1,02/03,Liga Portugal,6,10/07/02,Home,Sporting CP,Moreirense FC,3:00,LW,Header,Rui Jorge,95.0,3,00
2,02/03,Liga Portugal,8,10/26/02,Away,Sporting CP,Boavista FC,1:02,Unknown,Right-footed shot,Carlos Martins,88.0,1,02
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,Home,Sporting CP,CD Estarreja,4:01,Unknown,Left-footed shot,Cesar Prates,67.0,4,01
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,Home,Sporting CP,FC Oliveira do Hospital,8:01,Unknown,NaN,Not Avaliable,13.0,8,01
5,03/04,Premier League,11,11/01/03,Home,Manchester United,Portsmouth FC,3:00,RW,Direct free kick,Not Avaliable,80.0,3,00
6,03/04,FA Cup,Fifth Round,2/14/04,Home,Manchester United,Manchester City,4:02,RW,Right-footed shot,Not Avaliable,74.0,4,02
7,03/04,Premier League,29,3/20/04,Home,Manchester United,Tottenham Hotspur,3:00,Unknown,Right-footed shot,Not Avaliable,89.0,3,00
8,03/04,Premier League,32,04/10/04,Away,Manchester United,Birmingham City,1:02,Unknown,Header,Ryan Giggs,60.0,1,02
9,03/04,Premier League,38,5/15/04,Away,Manchester United,Aston Villa,0:02,Unknown,Right-footed shot,Not Avaliable,4.0,0,02

In [52]:
df = df.rename(columns={'Result':'Match_Result'})

In [53]:
df.head(5)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Match_Result,Playing_Position,Type,Goal_assist,Total_Minutes_Match_Played,Ronaldo Team Goals,Opponent Team Goals
0,02/03,Liga Portugal,6,10/07/02,Home,Sporting CP,Moreirense FC,3:00,LW,Solo run,Not Avaliable,34.0,3,00
1,02/03,Liga Portugal,6,10/07/02,Home,Sporting CP,Moreirense FC,3:00,LW,Header,Rui Jorge,95.0,3,00
2,02/03,Liga Portugal,8,10/26/02,Away,Sporting CP,Boavista FC,1:02,Unknown,Right-footed shot,Carlos Martins,88.0,1,02
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,Home,Sporting CP,CD Estarreja,4:01,Unknown,Left-footed shot,Cesar Prates,67.0,4,01
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,Home,Sporting CP,FC Oliveira do Hospital,8:01,Unknown,NaN,Not Avaliable,13.0,8,01

In [54]:
df['Type']=df['Type'].fillna('Unknown')

In [55]:
df.head(5)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Match_Result,Playing_Position,Type,Goal_assist,Total_Minutes_Match_Played,Ronaldo Team Goals,Opponent Team Goals
0,02/03,Liga Portugal,6,10/07/02,Home,Sporting CP,Moreirense FC,3:00,LW,Solo run,Not Avaliable,34.0,3,00
1,02/03,Liga Portugal,6,10/07/02,Home,Sporting CP,Moreirense FC,3:00,LW,Header,Rui Jorge,95.0,3,00
2,02/03,Liga Portugal,8,10/26/02,Away,Sporting CP,Boavista FC,1:02,Unknown,Right-footed shot,Carlos Martins,88.0,1,02
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,Home,Sporting CP,CD Estarreja,4:01,Unknown,Left-footed shot,Cesar Prates,67.0,4,01
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,Home,Sporting CP,FC Oliveira do Hospital,8:01,Unknown,Unknown,Not Avaliable,13.0,8,01

In [56]:
df['Matchday'].unique()

array(['6', '8', 'Fourth Round', 'Fifth Round', '11', '29', '32', '38',
       'Final', '16', 'Third Round', '24', '25', 'Sixth Round', '30',
       'Semi-Finals', '3rd round', 'Round of 16', '20', '26', '28', '1',
       '10', '15', '17', '19', '21', '23', '6th round', 'Quarter-Finals',
       '37', 'Group Stage', '9', '12', '13', '18', '22', '27', 'last 16',
       '31', '33', '34', '36', '2', '3', '4', '35', '7', '4th round',
       '14', 'final', '5'], dtype=object)

In [57]:
group_mapping = {
    '1': 'Early Rounds',
    '2': 'Early Rounds',
    '3': 'Early Rounds',
    '4': 'Early Rounds',
    '5': 'Early Rounds',
    '6': 'Early Rounds',
    '7': 'Early Rounds',
    '8': 'Early Rounds',
    '9': 'Early Rounds',
    '10': 'Early Rounds',
    '11': 'Early Rounds',
    '12': 'Early Rounds',
    '13': 'Early Rounds',
    '14': 'Early Rounds',
    '15': 'Early Rounds',
    '16': 'Early Rounds',
    '17': 'Early Rounds',
    '18': 'Early Rounds',
    '19': 'Early Rounds',
    '20': 'Early Rounds',
    '21': 'Early Rounds',
    '22': 'Early Rounds',
    '23': 'Early Rounds',
    '24': 'Early Rounds',
    '25': 'Early Rounds',
    '26': 'Early Rounds',
    '27': 'Early Rounds',
    '28': 'Early Rounds',
    '29': 'Early Rounds',
    '30': 'Early Rounds',
    '31': 'Early Rounds',
    '32': 'Early Rounds',
    '33': 'Early Rounds',
    '34': 'Early Rounds',
    '35': 'Early Rounds',
    '36': 'Early Rounds',
    '37': 'Early Rounds',
    '38': 'Early Rounds',
    'Group Stage': 'Group Stage',
    'Final': 'Final',
    'Semi-Finals': 'Semi-Finals',
    'Quarter-Finals': 'Quarter-Finals',
    'Round of 16': 'Round of 16',
    'Third Round': 'Third Round',
    'Fourth Round': 'Fourth Round',
    'Fifth Round': 'Fifth Round',
    'Sixth Round': 'Sixth Round',
    'last 16': 'Last 16',
    'final': 'Final',
    '3rd round': 'Third Round',
    '4th round': 'Fourth Round',
    '6th round': 'Sixth Round',
}

# Replace values in the 'Matchday' column using the mapping dictionary
df['Matchday'] = df['Matchday'].replace(group_mapping)

df.head(5)

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Match_Result,Playing_Position,Type,Goal_assist,Total_Minutes_Match_Played,Ronaldo Team Goals,Opponent Team Goals
0,02/03,Liga Portugal,Early Rounds,10/07/02,Home,Sporting CP,Moreirense FC,3:00,LW,Solo run,Not Avaliable,34.0,3,00
1,02/03,Liga Portugal,Early Rounds,10/07/02,Home,Sporting CP,Moreirense FC,3:00,LW,Header,Rui Jorge,95.0,3,00
2,02/03,Liga Portugal,Early Rounds,10/26/02,Away,Sporting CP,Boavista FC,1:02,Unknown,Right-footed shot,Carlos Martins,88.0,1,02
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,Home,Sporting CP,CD Estarreja,4:01,Unknown,Left-footed shot,Cesar Prates,67.0,4,01
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,Home,Sporting CP,FC Oliveira do Hospital,8:01,Unknown,Unknown,Not Avaliable,13.0,8,01

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Season                      710 non-null    object
 1   Competition                 710 non-null    object
 2   Matchday                    710 non-null    object
 3   Date                        710 non-null    object
 4   Venue                       710 non-null    object
 5   Club                        710 non-null    object
 6   Opponent                    710 non-null    object
 7   Match_Result                710 non-null    object
 8   Playing_Position            710 non-null    object
 9   Type                        710 non-null    object
 10  Goal_assist                 710 non-null    object
 11  Total_Minutes_Match_Played  710 non-null    float64
 12  Ronaldo Team Goals          710 non-null    object
 13  Opponent Team Goals         710 non-null    object
dtypes: float64(1), object(13)
memory usage: 77.8+ KB

# Till here my Data is Fully Cleaned

Seperated Columns Replaced null values Made Date format Correct ETC Now Export Csv

In [59]:
df.to_csv('E:\Data Analyst Roadmap\Google Data Analytics Certificate Course\Different Analysis\Ronaldo_Cleaned.csv',index=False)

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Amish Ilyas\AppData\Local\Temp\ipykernel_9724\3566243204.py:1: SyntaxWarning: invalid escape sequence '\D'
  df.to_csv('E:\Data Analyst Roadmap\Google Data Analytics Certificate Course\Different Analysis\Ronaldo_Cleaned.csv',index=False)

In [63]:
df['Match_Result'] = df['Match_Result'].astype('str')

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Season                      710 non-null    object
 1   Competition                 710 non-null    object
 2   Matchday                    710 non-null    object
 3   Date                        710 non-null    object
 4   Venue                       710 non-null    object
 5   Club                        710 non-null    object
 6   Opponent                    710 non-null    object
 7   Match_Result                710 non-null    object
 8   Playing_Position            710 non-null    object
 9   Type                        710 non-null    object
 10  Goal_assist                 710 non-null    object
 11  Total_Minutes_Match_Played  710 non-null    float64
 12  Ronaldo Team Goals          710 non-null    object
 13  Opponent Team Goals         710 non-null    object
dtypes: float64(1), object(13)
memory usage: 77.8+ KB

In [70]:
df['Match_Result']=df['Match_Result'].str.replace(':','-')

In [71]:
df

,Season,Competition,Matchday,Date,Venue,Club,Opponent,Match_Result,Playing_Position,Type,Goal_assist,Total_Minutes_Match_Played,Ronaldo Team Goals,Opponent Team Goals
0,02/03,Liga Portugal,Early Rounds,10/07/02,Home,Sporting CP,Moreirense FC,3-00,LW,Solo run,Not Avaliable,34.0,3,00
1,02/03,Liga Portugal,Early Rounds,10/07/02,Home,Sporting CP,Moreirense FC,3-00,LW,Header,Rui Jorge,95.0,3,00
2,02/03,Liga Portugal,Early Rounds,10/26/02,Away,Sporting CP,Boavista FC,1-02,Unknown,Right-footed shot,Carlos Martins,88.0,1,02
3,02/03,Taca de Portugal Placard,Fourth Round,11/24/02,Home,Sporting CP,CD Estarreja,4-01,Unknown,Left-footed shot,Cesar Prates,67.0,4,01
4,02/03,Taca de Portugal Placard,Fifth Round,12/18/02,Home,Sporting CP,FC Oliveira do Hospital,8-01,Unknown,Unknown,Not Avaliable,13.0,8,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,22/23,Saudi Pro League,Early Rounds,2/9/23,Away,Al-Nassr FC,Al-Wehda FC,0-4,CF,Right-footed shot,Not Avaliable,61.0,0,4
706,22/23,Saudi Pro League,Early Rounds,2/25/23,Away,Al-Nassr FC,Damac FC,0-3,CF,Penalty,,18.0,0,3
707,22/23,Saudi Pro League,Early Rounds,2/25/23,Away,Al-Nassr FC,Damac FC,0-3,CF,Left-footed shot,Sultan Al-Ghannam,23.0,0,3
708,22/23,Saudi Pro League,Early Rounds,2/25/23,Away,Al-Nassr FC,Damac FC,0-3,CF,Counter attack goal,Ayman Yahya,44.0,0,3
709,22/23,Saudi Pro League,Early Rounds,3/18/23,Home,Al-Nassr FC,Abha Club,2-1,CF,Direct free kick,Not Avaliable,78.0,2,1

In [73]:
df['Goal_assist'] = df['Goal_assist'].str.replace('Not Avaliable','Unknown')

In [74]:
df.to_excel('E:\Data Analyst Roadmap\Google Data Analytics Certificate Course\Different Analysis\Ronaldo Goals Analysis\RonaldoAnalysis.xlsx',index=False)

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Amish Ilyas\AppData\Local\Temp\ipykernel_9724\3060701464.py:1: SyntaxWarning: invalid escape sequence '\D'
  df.to_excel('E:\Data Analyst Roadmap\Google Data Analytics Certificate Course\Different Analysis\Ronaldo Goals Analysis\RonaldoAnalysis.xlsx',index=False)

In [75]:
df.to_csv('E:\Data Analyst Roadmap\Google Data Analytics Certificate Course\Different Analysis\Ronaldo Goals Analysis\RonaldoAnalysis.csv',index=False)

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Amish Ilyas\AppData\Local\Temp\ipykernel_9724\1628389712.py:1: SyntaxWarning: invalid escape sequence '\D'
  df.to_csv('E:\Data Analyst Roadmap\Google Data Analytics Certificate Course\Different Analysis\Ronaldo Goals Analysis\RonaldoAnalysis.csv',index=False)