In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv(r'E:\Data Analyst Roadmap\Google Data Analytics Certificate Course\Python\Alex the Analyst Playlist of Python\Pandas\LOTR.csv')

In [3]:
df2 = pd.read_csv(r'E:\Data Analyst Roadmap\Google Data Analytics Certificate Course\Python\Alex the Analyst Playlist of Python\Pandas\LOTR 2.csv')

In [4]:
df1

   FellowshipID FirstName     Skills
0          1001     Frodo     Hiding
1          1002   Samwise  Gardening
2          1003   Gandalf     Spells
3          1004    Pippin  Fireworks

In [5]:
df2

   FellowshipID FirstName   Age
0          1001     Frodo    50
1          1002   Samwise    39
2          1006   Legolas  2931
3          1007    Elrond  6520
4          1008  Barromir    51

In [21]:
inner_Join = df1.merge(df2,how='inner')

In [22]:
inner_Join

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

In [13]:
outer_join = df1.merge(df2,how='outer')

In [14]:
outer_join

   FellowshipID FirstName     Skills     Age
0          1001     Frodo     Hiding    50.0
1          1002   Samwise  Gardening    39.0
2          1003   Gandalf     Spells     NaN
3          1004    Pippin  Fireworks     NaN
4          1006   Legolas        NaN  2931.0
5          1007    Elrond        NaN  6520.0
6          1008  Barromir        NaN    51.0

In [15]:
left = df1.merge(df2,how='left')

In [16]:
left

   FellowshipID FirstName     Skills   Age
0          1001     Frodo     Hiding  50.0
1          1002   Samwise  Gardening  39.0
2          1003   Gandalf     Spells   NaN
3          1004    Pippin  Fireworks   NaN

In [17]:
right = df1.merge(df2,how='right')

In [18]:
right

   FellowshipID FirstName     Skills   Age
0          1001     Frodo     Hiding    50
1          1002   Samwise  Gardening    39
2          1006   Legolas        NaN  2931
3          1007    Elrond        NaN  6520
4          1008  Barromir        NaN    51

In [24]:
choice_value_inner_Join = df1.merge(df2,how='inner',on=['FellowshipID','FirstName'])

In [25]:
choice_value_inner_Join

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

In [26]:
choice_value_Outer_Join = df1.merge(df2,how='outer',on=['FellowshipID','FirstName'])

In [27]:
choice_value_Outer_Join

   FellowshipID FirstName     Skills     Age
0          1001     Frodo     Hiding    50.0
1          1002   Samwise  Gardening    39.0
2          1003   Gandalf     Spells     NaN
3          1004    Pippin  Fireworks     NaN
4          1006   Legolas        NaN  2931.0
5          1007    Elrond        NaN  6520.0
6          1008  Barromir        NaN    51.0