In [2]:
import pandas as pd

In [3]:
df = pd.read_excel(r'E:\Data Analyst Roadmap\Google Data Analytics Certificate Course\Python\Alex the Analyst Playlist of Python\Pandas\Movie-Data.xlsx')

In [4]:
df

,Movie Title,Release Date,Wikipedia URL,Genre,Director (1),Director (2),Cast (1),Cast (2),Cast (3),Cast (4),Cast (5),Budget,Revenue
0,10 Cloverfield Lane,2016-03-08,https://en.wikipedia.org/wiki/10_Cloverfield_Lane,Thriller,Dan Trachtenberg,NaN,Mary Elizabeth Winstead,John Goodman,John Gallagher,NaN,NaN,15000000,108300000
1,13 Hours: The Secret Soldiers of Benghazi,2016-01-15,https://en.wikipedia.org/wiki/13_Hours:_The_Se...,Action,Michael Bay,NaN,James Badge Dale,John Krasinski,Toby Stephens,Pablo Schreiber,Max Martini,45000000,69400000
2,2 Guns,2013-08-02,https://en.wikipedia.org/wiki/2_Guns,Action,Baltasar Kormákur,NaN,Mark Wahlberg,Denzel Washington,Paula Patton,Bill Paxton,Edward James Olmos,61000000,131900000
3,21 Jump Street,2012-03-16,https://en.wikipedia.org/wiki/21_Jump_Street_(...,Comedy,Phil Lord,Chris Miller,Jonah Hill,Channing Tatum,Ice Cube,Brie Larson,Rob Riggle,55000000,201500000
4,22 Jump Street,2014-06-04,https://en.wikipedia.org/wiki/22_Jump_Street,Action,Phil Lord,Chris Miller,Channing Tatum,Jonah Hill,Ice Cube,NaN,NaN,84500000,331300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,X-Men: Days of Future Past,2014-05-10,https://en.wikipedia.org/wiki/X-Men:_Days_of_F...,Action,Bryan Singer,NaN,Hugh Jackman,James McAvoy,Michael Fassbender,Halle Berry,Jennifer Lawrence,200000000,747900000
504,You're Next,2013-08-23,https://en.wikipedia.org/wiki/You%2527re_Next,Horror,Adam Wingard,NaN,Sharni Vinson,Joe Swanberg,AJ Bowen,Nicholas Tucci,Barbara Crampton,1000000,26800000
505,Zero Dark Thirty,2012-12-19,https://en.wikipedia.org/wiki/Zero_Dark_Thirty,Drama,Kathryn Bigelow,NaN,Jessica Chastain,Chris Pratt,Joel Edgerton,Kyle Chandler,Jason Clarke,40000000,132800000
506,Zhong Kui: Snow Girl and the Dark Crystal,2015-02-19,https://en.wikipedia.org/wiki/Zhong_Kui:_Snow_...,Romance,Peter Pau,NaN,Li Bingbing,Chen Kun,Yang Zishan,Winston Chao,Bao Bei'er,30000000,64470000
507,Zoolander 2,2016-02-12,https://en.wikipedia.org/wiki/Zoolander_2,Comedy,Ben Stiller,NaN,Ben Stiller,Owen Wilson,Christine Taylor,Will Ferrell,Penélope Cruz,50000000,56000000

In [5]:
Genres_Sum_Revenue = df.groupby('Genre').agg({'Revenue':'sum'})

In [11]:
Genres_Sum_Revenue.sort_values(by='Revenue',ascending=False)

                 Revenue
Genre
Action       28060740000
Comedy       12097400000
Drama         7208140000
Sci-Fi        7152420000
Adventure     6481300000
Horror        3252800000
Family        3251500000
Fantasy       2446100000
Thriller      2191000000
Crime         1326400000
Biography      882100000
Animation      828600000
Romance        698170000
Musical        520000000
Mystery        483900000
Religious      258400000
Documentary     68500000

In [12]:
Count_of_Movies = df.count()

In [13]:
Count_of_Movies

Movie Title      508
Release Date     508
Wikipedia URL    508
Genre            508
Director (1)     508
Director (2)      41
Cast (1)         508
Cast (2)         503
Cast (3)         485
Cast (4)         452
Cast (5)         389
Budget           508
Revenue          508
dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 508 entries, 0 to 507
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Movie Title    508 non-null    object
 1   Release Date   508 non-null    datetime64[ns]
 2   Wikipedia URL  508 non-null    object
 3   Genre          508 non-null    object
 4   Director (1)   508 non-null    object
 5   Director (2)   41 non-null     object
 6   Cast (1)       508 non-null    object
 7   Cast (2)       503 non-null    object
 8   Cast (3)       485 non-null    object
 9   Cast (4)       452 non-null    object
 10  Cast (5)       389 non-null    object
 11  Budget         508 non-null    int64
 12  Revenue        508 non-null    int64
dtypes: datetime64[ns](1), int64(2), object(10)
memory usage: 51.7+ KB

In [17]:
Count_Of_Movies_By_Genre = df.groupby('Genre').agg({'Genre':['count']})

In [20]:
Count_Of_Movies_By_Genre

            Genre
            count
Genre
Action        120
Adventure      21
Animation       3
Biography      15
Comedy         98
Crime          23
Documentary     1
Drama          89
Family         12
Fantasy        10
Horror         43
Musical         4
Mystery         5
Religious       7
Romance        13
Sci-Fi         28
Thriller       16

In [21]:
df

,Movie Title,Release Date,Wikipedia URL,Genre,Director (1),Director (2),Cast (1),Cast (2),Cast (3),Cast (4),Cast (5),Budget,Revenue
0,10 Cloverfield Lane,2016-03-08,https://en.wikipedia.org/wiki/10_Cloverfield_Lane,Thriller,Dan Trachtenberg,NaN,Mary Elizabeth Winstead,John Goodman,John Gallagher,NaN,NaN,15000000,108300000
1,13 Hours: The Secret Soldiers of Benghazi,2016-01-15,https://en.wikipedia.org/wiki/13_Hours:_The_Se...,Action,Michael Bay,NaN,James Badge Dale,John Krasinski,Toby Stephens,Pablo Schreiber,Max Martini,45000000,69400000
2,2 Guns,2013-08-02,https://en.wikipedia.org/wiki/2_Guns,Action,Baltasar Kormákur,NaN,Mark Wahlberg,Denzel Washington,Paula Patton,Bill Paxton,Edward James Olmos,61000000,131900000
3,21 Jump Street,2012-03-16,https://en.wikipedia.org/wiki/21_Jump_Street_(...,Comedy,Phil Lord,Chris Miller,Jonah Hill,Channing Tatum,Ice Cube,Brie Larson,Rob Riggle,55000000,201500000
4,22 Jump Street,2014-06-04,https://en.wikipedia.org/wiki/22_Jump_Street,Action,Phil Lord,Chris Miller,Channing Tatum,Jonah Hill,Ice Cube,NaN,NaN,84500000,331300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,X-Men: Days of Future Past,2014-05-10,https://en.wikipedia.org/wiki/X-Men:_Days_of_F...,Action,Bryan Singer,NaN,Hugh Jackman,James McAvoy,Michael Fassbender,Halle Berry,Jennifer Lawrence,200000000,747900000
504,You're Next,2013-08-23,https://en.wikipedia.org/wiki/You%2527re_Next,Horror,Adam Wingard,NaN,Sharni Vinson,Joe Swanberg,AJ Bowen,Nicholas Tucci,Barbara Crampton,1000000,26800000
505,Zero Dark Thirty,2012-12-19,https://en.wikipedia.org/wiki/Zero_Dark_Thirty,Drama,Kathryn Bigelow,NaN,Jessica Chastain,Chris Pratt,Joel Edgerton,Kyle Chandler,Jason Clarke,40000000,132800000
506,Zhong Kui: Snow Girl and the Dark Crystal,2015-02-19,https://en.wikipedia.org/wiki/Zhong_Kui:_Snow_...,Romance,Peter Pau,NaN,Li Bingbing,Chen Kun,Yang Zishan,Winston Chao,Bao Bei'er,30000000,64470000
507,Zoolander 2,2016-02-12,https://en.wikipedia.org/wiki/Zoolander_2,Comedy,Ben Stiller,NaN,Ben Stiller,Owen Wilson,Christine Taylor,Will Ferrell,Penélope Cruz,50000000,56000000

In [46]:
Top_10_Movies_By_Budget = df.groupby('Movie Title').sum('Budget')

In [49]:
Top_10_Movies_By_Budget.sort_values(by='Budget',ascending=False)

                                              Budget    Revenue
Movie Title
Batman v Superman: Dawn of Justice         250000000  872700000
The Hobbit: The Battle of the Five Armies  250000000  956000000
Dawn of the Planet of the Apes             235000000  710600000
The Amazing Spider-Man                     230000000  757900000
Man of Steel                               225000000  668000000
...                                              ...        ...
Unfriended                                   1000000   64100000
The Devil Inside                             1000000  101800000
The Letters                                  1000000    1600000
Chernobyl Diaries                            1000000   37200000
You're Next                                  1000000   26800000

[508 rows x 2 columns]

In [54]:
Top_10_Movies_By_Budget.sort_values(by='Budget',ascending=False).head(10)

                                              Budget    Revenue
Movie Title
Batman v Superman: Dawn of Justice         250000000  872700000
The Hobbit: The Battle of the Five Armies  250000000  956000000
Dawn of the Planet of the Apes             235000000  710600000
The Amazing Spider-Man                     230000000  757900000
Man of Steel                               225000000  668000000
Battleship                                 220000000  303000000
Men in Black 3                             215000000  624000000
X-Men: Days of Future Past                 200000000  747900000
Pacific Rim                                190000000  411000000
World War Z                                190000000  540000000

In [59]:
top_10_Movies_By_Revenue = df.groupby('Movie Title').agg({'Revenue':'sum'})

In [60]:
top_10_Movies_By_Revenue.sort_values('Revenue',ascending=False).head(10)

                                             Revenue
Movie Title
Despicable Me 2                            970800000
The Hobbit: The Battle of the Five Armies  956000000
Ice Age: Continental Drift                 877000000
Batman v Superman: Dawn of Justice         872700000
The Twilight Saga: Breaking Dawn – Part 2  829700000
Fast & Furious 6                           788700000
Deadpool                                   782600000
The Amazing Spider-Man                     757900000
The Hunger Games: Mockingjay – Part 1      755400000
X-Men: Days of Future Past                 747900000

In [73]:
top_10_Movies_With_Lowest_Budget_Highest_Revenue = df.groupby(['Movie Title','Genre']).agg({'Budget':'sum','Revenue':'sum'})

In [76]:
top_10_Movies_With_Lowest_Budget_Highest_Revenue.sort_values(by=['Budget','Revenue'],ascending=[True,False]).head(10)

                                   Budget    Revenue
Movie Title            Genre
The Devil Inside       Horror     1000000  101800000
Unfriended             Horror     1000000   64100000
Chernobyl Diaries      Horror     1000000   37200000
You're Next            Horror     1000000   26800000
The Letters            Drama      1000000    1600000
The Raid: Redemption ₪ Action     1100000    9140000
Mustang                Drama      1300000    4900000
Embrace of the Serpent Adventure  1400000    2800000
Declaration of War     Romance    1500000    6500000
Son of Saul            Drama      1500000    6200000