In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel(r'E:\Data Analyst Roadmap\Google Data Analytics Certificate Course\Python\Alex the Analyst Playlist of Python\Pandas\Movie-Data.xlsx')

In [ ]:
df.shape

In [ ]:
df.head()

In [ ]:
df

In [22]:
df2 =pd.set_option('display.max.rows',10)

In [ ]:
df2 = df

In [23]:
df

,Movie Title,Release Date,Wikipedia URL,Genre,Director (1),Director (2),Cast (1),Cast (2),Cast (3),Cast (4),Cast (5),Budget,Revenue
0,10 Cloverfield Lane,2016-03-08,https://en.wikipedia.org/wiki/10_Cloverfield_Lane,Thriller,Dan Trachtenberg,NaN,Mary Elizabeth Winstead,John Goodman,John Gallagher,NaN,NaN,15000000,108300000
1,13 Hours: The Secret Soldiers of Benghazi,2016-01-15,https://en.wikipedia.org/wiki/13_Hours:_The_Se...,Action,Michael Bay,NaN,James Badge Dale,John Krasinski,Toby Stephens,Pablo Schreiber,Max Martini,45000000,69400000
2,2 Guns,2013-08-02,https://en.wikipedia.org/wiki/2_Guns,Action,Baltasar Kormákur,NaN,Mark Wahlberg,Denzel Washington,Paula Patton,Bill Paxton,Edward James Olmos,61000000,131900000
3,21 Jump Street,2012-03-16,https://en.wikipedia.org/wiki/21_Jump_Street_(...,Comedy,Phil Lord,Chris Miller,Jonah Hill,Channing Tatum,Ice Cube,Brie Larson,Rob Riggle,55000000,201500000
4,22 Jump Street,2014-06-04,https://en.wikipedia.org/wiki/22_Jump_Street,Action,Phil Lord,Chris Miller,Channing Tatum,Jonah Hill,Ice Cube,NaN,NaN,84500000,331300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,X-Men: Days of Future Past,2014-05-10,https://en.wikipedia.org/wiki/X-Men:_Days_of_F...,Action,Bryan Singer,NaN,Hugh Jackman,James McAvoy,Michael Fassbender,Halle Berry,Jennifer Lawrence,200000000,747900000
504,You're Next,2013-08-23,https://en.wikipedia.org/wiki/You%2527re_Next,Horror,Adam Wingard,NaN,Sharni Vinson,Joe Swanberg,AJ Bowen,Nicholas Tucci,Barbara Crampton,1000000,26800000
505,Zero Dark Thirty,2012-12-19,https://en.wikipedia.org/wiki/Zero_Dark_Thirty,Drama,Kathryn Bigelow,NaN,Jessica Chastain,Chris Pratt,Joel Edgerton,Kyle Chandler,Jason Clarke,40000000,132800000
506,Zhong Kui: Snow Girl and the Dark Crystal,2015-02-19,https://en.wikipedia.org/wiki/Zhong_Kui:_Snow_...,Romance,Peter Pau,NaN,Li Bingbing,Chen Kun,Yang Zishan,Winston Chao,Bao Bei'er,30000000,64470000
507,Zoolander 2,2016-02-12,https://en.wikipedia.org/wiki/Zoolander_2,Comedy,Ben Stiller,NaN,Ben Stiller,Owen Wilson,Christine Taylor,Will Ferrell,Penélope Cruz,50000000,56000000

In [24]:
df.head()

,Movie Title,Release Date,Wikipedia URL,Genre,Director (1),Director (2),Cast (1),Cast (2),Cast (3),Cast (4),Cast (5),Budget,Revenue
0,10 Cloverfield Lane,2016-03-08,https://en.wikipedia.org/wiki/10_Cloverfield_Lane,Thriller,Dan Trachtenberg,NaN,Mary Elizabeth Winstead,John Goodman,John Gallagher,NaN,NaN,15000000,108300000
1,13 Hours: The Secret Soldiers of Benghazi,2016-01-15,https://en.wikipedia.org/wiki/13_Hours:_The_Se...,Action,Michael Bay,NaN,James Badge Dale,John Krasinski,Toby Stephens,Pablo Schreiber,Max Martini,45000000,69400000
2,2 Guns,2013-08-02,https://en.wikipedia.org/wiki/2_Guns,Action,Baltasar Kormákur,NaN,Mark Wahlberg,Denzel Washington,Paula Patton,Bill Paxton,Edward James Olmos,61000000,131900000
3,21 Jump Street,2012-03-16,https://en.wikipedia.org/wiki/21_Jump_Street_(...,Comedy,Phil Lord,Chris Miller,Jonah Hill,Channing Tatum,Ice Cube,Brie Larson,Rob Riggle,55000000,201500000
4,22 Jump Street,2014-06-04,https://en.wikipedia.org/wiki/22_Jump_Street,Action,Phil Lord,Chris Miller,Channing Tatum,Jonah Hill,Ice Cube,NaN,NaN,84500000,331300000

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 508 entries, 0 to 507
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Movie Title    508 non-null    object
 1   Release Date   508 non-null    datetime64[ns]
 2   Wikipedia URL  508 non-null    object
 3   Genre          508 non-null    object
 4   Director (1)   508 non-null    object
 5   Director (2)   41 non-null     object
 6   Cast (1)       508 non-null    object
 7   Cast (2)       503 non-null    object
 8   Cast (3)       485 non-null    object
 9   Cast (4)       452 non-null    object
 10  Cast (5)       389 non-null    object
 11  Budget         508 non-null    int64
 12  Revenue        508 non-null    int64
dtypes: datetime64[ns](1), int64(2), object(10)
memory usage: 51.7+ KB

In [26]:
df.head()

,Movie Title,Release Date,Wikipedia URL,Genre,Director (1),Director (2),Cast (1),Cast (2),Cast (3),Cast (4),Cast (5),Budget,Revenue
0,10 Cloverfield Lane,2016-03-08,https://en.wikipedia.org/wiki/10_Cloverfield_Lane,Thriller,Dan Trachtenberg,NaN,Mary Elizabeth Winstead,John Goodman,John Gallagher,NaN,NaN,15000000,108300000
1,13 Hours: The Secret Soldiers of Benghazi,2016-01-15,https://en.wikipedia.org/wiki/13_Hours:_The_Se...,Action,Michael Bay,NaN,James Badge Dale,John Krasinski,Toby Stephens,Pablo Schreiber,Max Martini,45000000,69400000
2,2 Guns,2013-08-02,https://en.wikipedia.org/wiki/2_Guns,Action,Baltasar Kormákur,NaN,Mark Wahlberg,Denzel Washington,Paula Patton,Bill Paxton,Edward James Olmos,61000000,131900000
3,21 Jump Street,2012-03-16,https://en.wikipedia.org/wiki/21_Jump_Street_(...,Comedy,Phil Lord,Chris Miller,Jonah Hill,Channing Tatum,Ice Cube,Brie Larson,Rob Riggle,55000000,201500000
4,22 Jump Street,2014-06-04,https://en.wikipedia.org/wiki/22_Jump_Street,Action,Phil Lord,Chris Miller,Channing Tatum,Jonah Hill,Ice Cube,NaN,NaN,84500000,331300000

In [29]:
Thriller_Movies = df[df['Genre'].str.contains('Thriller')]

In [45]:
df2 = Thriller_Movies

In [41]:
Countries_First = df.set_index('Genre')

In [43]:
Countries_First

,Movie Title,Release Date,Wikipedia URL,Director (1),Director (2),Cast (1),Cast (2),Cast (3),Cast (4),Cast (5),Budget,Revenue
Genre,,,,,,,,,,,,
Thriller,10 Cloverfield Lane,2016-03-08,https://en.wikipedia.org/wiki/10_Cloverfield_Lane,Dan Trachtenberg,NaN,Mary Elizabeth Winstead,John Goodman,John Gallagher,NaN,NaN,15000000,108300000
Thriller,A Most Wanted Man,2014-01-19,https://en.wikipedia.org/wiki/A_Most_Wanted_Ma...,Anton Corbijn,NaN,Philip Seymour Hoffman,Rachel McAdams,Robin Wright,Willem Dafoe,Grigoriy Dobrygin,15000000,36200000
Thriller,Don't Breathe,2016-08-26,https://en.wikipedia.org/wiki/Don%2527t_Breath...,Fede Alvarez,NaN,Dylan Minnette,Stephen Lang,Daniel Zovatto,NaN,NaN,9900000,28300000
Thriller,Eye in the Sky,2015-09-11,https://en.wikipedia.org/wiki/Eye_in_the_Sky_(...,Gavin Hood,NaN,Helen Mirren,Aaron Paul,Alan Rickman,Barkhad Abdi,NaN,13000000,32800000
Thriller,Nerve,2016-07-27,https://en.wikipedia.org/wiki/Nerve_(2016_film),Henry Joost,Ariel Schulman,Dave Franco,Emma Roberts,Emily Meade,Kimiko Glenn,Juliette Lewis,20000000,47600000
...,...,...,...,...,...,...,...,...,...,...,...,...
Thriller,The Gunman,2015-03-20,https://en.wikipedia.org/wiki/The_Gunman_(film),Pierre Morel,NaN,Sean Penn,Javier Bardem,Ray Winstone,Idris Elba,Mark Rylance,40000000,24200000
Thriller,The November Man,2014-08-27,https://en.wikipedia.org/wiki/The_November_Man,Roger Donaldson,NaN,Pierce Brosnan,Olga Kurylenko,Luke Bracey,Bill Smitrovich,Will Patton,15000000,34800000
Thriller,The Perfect Guy,2015-09-02,https://en.wikipedia.org/wiki/The_Perfect_Guy_...,David M. Rosenthal,NaN,Sanaa Lathan,Michael Ealy,Morris Chestnut,NaN,NaN,18000000,60300000
Thriller,The Raven,2012-04-27,https://en.wikipedia.org/wiki/The_Raven_(2012_...,James McTeigue,NaN,John Cusack,Alice Eve,Luke Evans,Brendan Gleeson,Oliver Jackson-Cohen,26000000,29700000
Thriller,The Revenant,2015-12-25,https://en.wikipedia.org/wiki/The_Revenant_(20...,Alejandro G. Iñárritu,NaN,Leonardo DiCaprio,Tom Hardy,Domhnall Gleeson,Will Poulter,NaN,135000000,533000000

In [44]:
df

,Movie Title,Release Date,Wikipedia URL,Genre,Director (1),Director (2),Cast (1),Cast (2),Cast (3),Cast (4),Cast (5),Budget,Revenue
0,10 Cloverfield Lane,2016-03-08,https://en.wikipedia.org/wiki/10_Cloverfield_Lane,Thriller,Dan Trachtenberg,NaN,Mary Elizabeth Winstead,John Goodman,John Gallagher,NaN,NaN,15000000,108300000
14,A Most Wanted Man,2014-01-19,https://en.wikipedia.org/wiki/A_Most_Wanted_Ma...,Thriller,Anton Corbijn,NaN,Philip Seymour Hoffman,Rachel McAdams,Robin Wright,Willem Dafoe,Grigoriy Dobrygin,15000000,36200000
88,Don't Breathe,2016-08-26,https://en.wikipedia.org/wiki/Don%2527t_Breath...,Thriller,Fede Alvarez,NaN,Dylan Minnette,Stephen Lang,Daniel Zovatto,NaN,NaN,9900000,28300000
106,Eye in the Sky,2015-09-11,https://en.wikipedia.org/wiki/Eye_in_the_Sky_(...,Thriller,Gavin Hood,NaN,Helen Mirren,Aaron Paul,Alan Rickman,Barkhad Abdi,NaN,13000000,32800000
220,Nerve,2016-07-27,https://en.wikipedia.org/wiki/Nerve_(2016_film),Thriller,Henry Joost,Ariel Schulman,Dave Franco,Emma Roberts,Emily Meade,Kimiko Glenn,Juliette Lewis,20000000,47600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
376,The Gunman,2015-03-20,https://en.wikipedia.org/wiki/The_Gunman_(film),Thriller,Pierre Morel,NaN,Sean Penn,Javier Bardem,Ray Winstone,Idris Elba,Mark Rylance,40000000,24200000
416,The November Man,2014-08-27,https://en.wikipedia.org/wiki/The_November_Man,Thriller,Roger Donaldson,NaN,Pierce Brosnan,Olga Kurylenko,Luke Bracey,Bill Smitrovich,Will Patton,15000000,34800000
421,The Perfect Guy,2015-09-02,https://en.wikipedia.org/wiki/The_Perfect_Guy_...,Thriller,David M. Rosenthal,NaN,Sanaa Lathan,Michael Ealy,Morris Chestnut,NaN,NaN,18000000,60300000
431,The Raven,2012-04-27,https://en.wikipedia.org/wiki/The_Raven_(2012_...,Thriller,James McTeigue,NaN,John Cusack,Alice Eve,Luke Evans,Brendan Gleeson,Oliver Jackson-Cohen,26000000,29700000
432,The Revenant,2015-12-25,https://en.wikipedia.org/wiki/The_Revenant_(20...,Thriller,Alejandro G. Iñárritu,NaN,Leonardo DiCaprio,Tom Hardy,Domhnall Gleeson,Will Poulter,NaN,135000000,533000000

In [46]:
df

,Movie Title,Release Date,Wikipedia URL,Genre,Director (1),Director (2),Cast (1),Cast (2),Cast (3),Cast (4),Cast (5),Budget,Revenue
0,10 Cloverfield Lane,2016-03-08,https://en.wikipedia.org/wiki/10_Cloverfield_Lane,Thriller,Dan Trachtenberg,NaN,Mary Elizabeth Winstead,John Goodman,John Gallagher,NaN,NaN,15000000,108300000
14,A Most Wanted Man,2014-01-19,https://en.wikipedia.org/wiki/A_Most_Wanted_Ma...,Thriller,Anton Corbijn,NaN,Philip Seymour Hoffman,Rachel McAdams,Robin Wright,Willem Dafoe,Grigoriy Dobrygin,15000000,36200000
88,Don't Breathe,2016-08-26,https://en.wikipedia.org/wiki/Don%2527t_Breath...,Thriller,Fede Alvarez,NaN,Dylan Minnette,Stephen Lang,Daniel Zovatto,NaN,NaN,9900000,28300000
106,Eye in the Sky,2015-09-11,https://en.wikipedia.org/wiki/Eye_in_the_Sky_(...,Thriller,Gavin Hood,NaN,Helen Mirren,Aaron Paul,Alan Rickman,Barkhad Abdi,NaN,13000000,32800000
220,Nerve,2016-07-27,https://en.wikipedia.org/wiki/Nerve_(2016_film),Thriller,Henry Joost,Ariel Schulman,Dave Franco,Emma Roberts,Emily Meade,Kimiko Glenn,Juliette Lewis,20000000,47600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
376,The Gunman,2015-03-20,https://en.wikipedia.org/wiki/The_Gunman_(film),Thriller,Pierre Morel,NaN,Sean Penn,Javier Bardem,Ray Winstone,Idris Elba,Mark Rylance,40000000,24200000
416,The November Man,2014-08-27,https://en.wikipedia.org/wiki/The_November_Man,Thriller,Roger Donaldson,NaN,Pierce Brosnan,Olga Kurylenko,Luke Bracey,Bill Smitrovich,Will Patton,15000000,34800000
421,The Perfect Guy,2015-09-02,https://en.wikipedia.org/wiki/The_Perfect_Guy_...,Thriller,David M. Rosenthal,NaN,Sanaa Lathan,Michael Ealy,Morris Chestnut,NaN,NaN,18000000,60300000
431,The Raven,2012-04-27,https://en.wikipedia.org/wiki/The_Raven_(2012_...,Thriller,James McTeigue,NaN,John Cusack,Alice Eve,Luke Evans,Brendan Gleeson,Oliver Jackson-Cohen,26000000,29700000
432,The Revenant,2015-12-25,https://en.wikipedia.org/wiki/The_Revenant_(20...,Thriller,Alejandro G. Iñárritu,NaN,Leonardo DiCaprio,Tom Hardy,Domhnall Gleeson,Will Poulter,NaN,135000000,533000000

In [47]:
df = pd.read_excel(r'E:\Data Analyst Roadmap\Google Data Analytics Certificate Course\Python\Alex the Analyst Playlist of Python\Pandas\Movie-Data.xlsx')

In [48]:
df

,Movie Title,Release Date,Wikipedia URL,Genre,Director (1),Director (2),Cast (1),Cast (2),Cast (3),Cast (4),Cast (5),Budget,Revenue
0,10 Cloverfield Lane,2016-03-08,https://en.wikipedia.org/wiki/10_Cloverfield_Lane,Thriller,Dan Trachtenberg,NaN,Mary Elizabeth Winstead,John Goodman,John Gallagher,NaN,NaN,15000000,108300000
1,13 Hours: The Secret Soldiers of Benghazi,2016-01-15,https://en.wikipedia.org/wiki/13_Hours:_The_Se...,Action,Michael Bay,NaN,James Badge Dale,John Krasinski,Toby Stephens,Pablo Schreiber,Max Martini,45000000,69400000
2,2 Guns,2013-08-02,https://en.wikipedia.org/wiki/2_Guns,Action,Baltasar Kormákur,NaN,Mark Wahlberg,Denzel Washington,Paula Patton,Bill Paxton,Edward James Olmos,61000000,131900000
3,21 Jump Street,2012-03-16,https://en.wikipedia.org/wiki/21_Jump_Street_(...,Comedy,Phil Lord,Chris Miller,Jonah Hill,Channing Tatum,Ice Cube,Brie Larson,Rob Riggle,55000000,201500000
4,22 Jump Street,2014-06-04,https://en.wikipedia.org/wiki/22_Jump_Street,Action,Phil Lord,Chris Miller,Channing Tatum,Jonah Hill,Ice Cube,NaN,NaN,84500000,331300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,X-Men: Days of Future Past,2014-05-10,https://en.wikipedia.org/wiki/X-Men:_Days_of_F...,Action,Bryan Singer,NaN,Hugh Jackman,James McAvoy,Michael Fassbender,Halle Berry,Jennifer Lawrence,200000000,747900000
504,You're Next,2013-08-23,https://en.wikipedia.org/wiki/You%2527re_Next,Horror,Adam Wingard,NaN,Sharni Vinson,Joe Swanberg,AJ Bowen,Nicholas Tucci,Barbara Crampton,1000000,26800000
505,Zero Dark Thirty,2012-12-19,https://en.wikipedia.org/wiki/Zero_Dark_Thirty,Drama,Kathryn Bigelow,NaN,Jessica Chastain,Chris Pratt,Joel Edgerton,Kyle Chandler,Jason Clarke,40000000,132800000
506,Zhong Kui: Snow Girl and the Dark Crystal,2015-02-19,https://en.wikipedia.org/wiki/Zhong_Kui:_Snow_...,Romance,Peter Pau,NaN,Li Bingbing,Chen Kun,Yang Zishan,Winston Chao,Bao Bei'er,30000000,64470000
507,Zoolander 2,2016-02-12,https://en.wikipedia.org/wiki/Zoolander_2,Comedy,Ben Stiller,NaN,Ben Stiller,Owen Wilson,Christine Taylor,Will Ferrell,Penélope Cruz,50000000,56000000

In [67]:
genreList = ['Action','Comedy','Horror']
#way1 = df[df['Genre'].str.contains('Action')]
way2 = df[df['Genre'].isin(genreList)].sort_values('Revenue',ascending=False)

In [68]:
way2

,Movie Title,Release Date,Wikipedia URL,Genre,Director (1),Director (2),Cast (1),Cast (2),Cast (3),Cast (4),Cast (5),Budget,Revenue
82,Despicable Me 2,2013-06-20,https://en.wikipedia.org/wiki/Despicable_Me_2,Comedy,Chris Renaud,Pierre Coffin,Steve Carell,Kristen Wiig,Miranda Cosgrove,Dana Gaier,Elsie Fisher,76000000,970800000
35,Batman v Superman: Dawn of Justice,2016-03-19,https://en.wikipedia.org/wiki/Batman_v_Superma...,Action,Zack Snyder,NaN,Ben Affleck,Henry Cavill,Amy Adams,Jesse Eisenberg,Diane Lane,250000000,872700000
108,Fast & Furious 6,2013-05-17,https://en.wikipedia.org/wiki/Fast_%2526_Furio...,Action,Justin Lin,NaN,Vin Diesel,Dwayne Johnson,Paul Walker,Michelle Rodriguez,Jordana Brewster,160000000,788700000
79,Deadpool,2016-02-08,https://en.wikipedia.org/wiki/Deadpool_(film),Action,Tim Miller,NaN,Ryan Reynolds,Gina Carano,T. J. Miller,Ed Skrein,Morena Baccarin,58000000,782600000
336,The Amazing Spider-Man,2012-07-03,https://en.wikipedia.org/wiki/The_Amazing_Spid...,Action,Marc Webb,NaN,Andrew Garfield,Emma Stone,Max Charles,Martin Sheen,Sally Field,230000000,757900000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
443,The Sweet Escape,2015-06-10,https://en.wikipedia.org/wiki/The_Sweet_Escape...,Comedy,Bruno Podalydès,NaN,Bruno Podalydès,Sandrine Kiberlain,Agnès Jaoui,Vimala Pons,NaN,3800000,3300000
161,Jane Got a Gun,2016-01-29,https://en.wikipedia.org/wiki/Jane_Got_a_Gun,Action,Gavin O'Connor,NaN,Natalie Portman,Joel Edgerton,Ewan McGregor,Rodrigo Santoro,Noah Emmerich,25000000,3000000
7,71,2014-02-07,https://en.wikipedia.org/wiki/%252771_(film),Action,Yann Demange,NaN,Jack O'Connell,Richard Dormer,Sean Harris,Sam Reid,NaN,8100000,2900000
475,Tusk,2014-09-06,https://en.wikipedia.org/wiki/Tusk_(2014_film),Horror,Kevin Smith,NaN,Michael Parks,Justin Long,Haley Joel Osment,Génesis Rodríguez,Johnny Depp,3000000,1900000
226,No One Lives,2013-05-10,https://en.wikipedia.org/wiki/No_One_Lives,Horror,Ryuhei Kitamura,NaN,Luke Evans,Adelaide Clemens,America Olivo,Derek Magyar,Lindsey Shaw,2900000,1000000

In [69]:
way2.set_index('Movie Title')

,Release Date,Wikipedia URL,Genre,Director (1),Director (2),Cast (1),Cast (2),Cast (3),Cast (4),Cast (5),Budget,Revenue
Movie Title,,,,,,,,,,,,
Despicable Me 2,2013-06-20,https://en.wikipedia.org/wiki/Despicable_Me_2,Comedy,Chris Renaud,Pierre Coffin,Steve Carell,Kristen Wiig,Miranda Cosgrove,Dana Gaier,Elsie Fisher,76000000,970800000
Batman v Superman: Dawn of Justice,2016-03-19,https://en.wikipedia.org/wiki/Batman_v_Superma...,Action,Zack Snyder,NaN,Ben Affleck,Henry Cavill,Amy Adams,Jesse Eisenberg,Diane Lane,250000000,872700000
Fast & Furious 6,2013-05-17,https://en.wikipedia.org/wiki/Fast_%2526_Furio...,Action,Justin Lin,NaN,Vin Diesel,Dwayne Johnson,Paul Walker,Michelle Rodriguez,Jordana Brewster,160000000,788700000
Deadpool,2016-02-08,https://en.wikipedia.org/wiki/Deadpool_(film),Action,Tim Miller,NaN,Ryan Reynolds,Gina Carano,T. J. Miller,Ed Skrein,Morena Baccarin,58000000,782600000
The Amazing Spider-Man,2012-07-03,https://en.wikipedia.org/wiki/The_Amazing_Spid...,Action,Marc Webb,NaN,Andrew Garfield,Emma Stone,Max Charles,Martin Sheen,Sally Field,230000000,757900000
...,...,...,...,...,...,...,...,...,...,...,...,...
The Sweet Escape,2015-06-10,https://en.wikipedia.org/wiki/The_Sweet_Escape...,Comedy,Bruno Podalydès,NaN,Bruno Podalydès,Sandrine Kiberlain,Agnès Jaoui,Vimala Pons,NaN,3800000,3300000
Jane Got a Gun,2016-01-29,https://en.wikipedia.org/wiki/Jane_Got_a_Gun,Action,Gavin O'Connor,NaN,Natalie Portman,Joel Edgerton,Ewan McGregor,Rodrigo Santoro,Noah Emmerich,25000000,3000000
71,2014-02-07,https://en.wikipedia.org/wiki/%252771_(film),Action,Yann Demange,NaN,Jack O'Connell,Richard Dormer,Sean Harris,Sam Reid,NaN,8100000,2900000
Tusk,2014-09-06,https://en.wikipedia.org/wiki/Tusk_(2014_film),Horror,Kevin Smith,NaN,Michael Parks,Justin Long,Haley Joel Osment,Génesis Rodríguez,Johnny Depp,3000000,1900000
No One Lives,2013-05-10,https://en.wikipedia.org/wiki/No_One_Lives,Horror,Ryuhei Kitamura,NaN,Luke Evans,Adelaide Clemens,America Olivo,Derek Magyar,Lindsey Shaw,2900000,1000000

In [80]:
way2.filter(items=[],axis=0)

Empty DataFrame
Columns: [Movie Title, Release Date, Wikipedia URL, Genre, Director (1), Director (2), Cast (1), Cast (2), Cast (3), Cast (4), Cast (5), Budget, Revenue]
Index: []

In [84]:
df2.filter(like='A Most ',axis=0)

Empty DataFrame
Columns: [Movie Title, Release Date, Wikipedia URL, Genre, Director (1), Director (2), Cast (1), Cast (2), Cast (3), Cast (4), Cast (5), Budget, Revenue]
Index: []

In [87]:
Movies = df.set_index('Movie Title')

In [94]:
Movies.sort_values(['Revenue'],ascending=False).filter(items=['Revenue','Budget'],axis=1)

                                               Revenue     Budget
Movie Title
Despicable Me 2                              970800000   76000000
The Hobbit: The Battle of the Five Armies    956000000  250000000
Ice Age: Continental Drift                   877000000   95000000
Batman v Superman: Dawn of Justice           872700000  250000000
The Twilight Saga: Breaking Dawn – Part 2    829700000  120000000
...                                                ...        ...
The Letters                                    1600000    1000000
Lazer Team                                     1600000    2400000
The Oogieloves in the Big Balloon Adventure    1100000   20000000
Ain't Them Bodies Saints                       1000000    4000000
No One Lives                                   1000000    2900000

[508 rows x 2 columns]

In [100]:
sorted_movies = Movies.sort_values(['Revenue'],ascending=False).filter(items=['Revenue','Budget'],axis=1)

In [101]:
sorted_movies

                                               Revenue     Budget
Movie Title
Despicable Me 2                              970800000   76000000
The Hobbit: The Battle of the Five Armies    956000000  250000000
Ice Age: Continental Drift                   877000000   95000000
Batman v Superman: Dawn of Justice           872700000  250000000
The Twilight Saga: Breaking Dawn – Part 2    829700000  120000000
...                                                ...        ...
The Letters                                    1600000    1000000
Lazer Team                                     1600000    2400000
The Oogieloves in the Big Balloon Adventure    1100000   20000000
Ain't Them Bodies Saints                       1000000    4000000
No One Lives                                   1000000    2900000

[508 rows x 2 columns]

In [107]:
sorted_movies.filter(like='Desp',axis=0)

                   Revenue    Budget
Movie Title
Despicable Me 2  970800000  76000000